README.md, app/Modules/NetworkData/Models/Atc.php
Renamed networkdata_atc to statistic_atc in Model.
Forgot readme updates on release.
=> Fixed NetworkData error

README.md, app/Modules/Community/Database/Migrations/2016_12_19_141500_fix_production_group_relationships.php, app/Modules/Community/Exceptions/Membership/AlreadyAGroupTierMemberException.php, app/Modules/Community/Models/Group.php, app/Modules/Community/Tests/unit/GroupMembershipTest.php, app/Modules/Community/Traits/CommunityAccount.php, composer.json, composer.lock, phpunit.xml, resources/views/adm/layout.blade.php, resources/views/layout.blade.php
group_id and account_id are the wrong way around in the membership table.
This has been rectified and extra tests added to verify this change.
=> Patch - fix group membership table names

.travis.yml, app/Modules/Community/Http/Controllers/Site/Membership.php, app/Modules/Community/Models/Group.php, app/Modules/Community/Resources/Views/site/membership/deploy.blade.php, app/Modules/Community/Tests/unit/GroupMembershipTest.php, composer.json, composer.lock
Fixes issue #682 - Prevents member from being given a "cannot join" error when they choose UK for the 2nd time.
=> Fixes issue #682 - Gracefully return to dashboard on multiple UK joins.

app/Console/Commands/Command.php
Fixes #782 
Checks to see if verbosity is specified
=> WSLogging Verbosity

app/Models/Sys/Token.php
=> Fixes #827 - Invalid reference to attribute value in Token model

CONTRIBUTING.md
Include a short guide on accessing the admin panel
=> Include section on accessing the admin panel

app/Modules/Visittransfer/Exceptions/Application/ApplicationNotRejectableException.php, app/Modules/Visittransfer/Models/Application.php
Presently limited to under review.
=> Hotfix: Allow applications to be rejected once submitted

app/Http/Controllers/Sso/Security.php, app/Models/Sso/Token.php, database/migrations/2017_02_10_232137_add_request_ip_and_used_at_to_sso_tokens.php, database/migrations/2017_02_10_232137_add_request_ip_to_sso_tokens.php
- Added migration to create a new `request_ip` column in sso_tokens
- Implemented new column in SSO/Security when a new token is generated
- New column that is set when the token is used
Closes #847
=> Log the IP from which a token was requested

app/Modules/Visittransfer/Policies/ApplicationPolicy.php
Change the `Gate` to authorise a check change when the application is in the open phase
Closes #904
=> Allow V/T 'checks' to be marked complete when open

app/Modules/Visittransfer/Resources/Views/admin/application/view.blade.php
=> VT Adm Application: Correct "unvailable" Typo

app/Modules/Visittransfer/Resources/Views/site/dashboard.blade.php, composer.lock, resources/assets/sass/app.scss, resources/views/layout.blade.php, resources/views/mship/management/dashboard.blade.php
Navbar now drops down on mobile to show menu. I also adjusted a few gutters to have grids align more nicely (alerts/dashboard content not being aligned, transfer boxes were misaligned, etc.)
Closes #436
=> Updated navbar/layout to show on mobile (for #436)

CONTRIBUTING.md, app/Console/Commands/SlackManager.php, app/Http/Controllers/Webhook/Slack.php, app/Notifications/ApplicationAccepted.php, app/Notifications/ApplicationReferenceAccepted.php, app/Notifications/ApplicationReferenceCancelled.php, app/Notifications/ApplicationReferenceRejected.php, app/Notifications/ApplicationReferenceRequest.php, app/Notifications/ApplicationReferenceSubmitted.php, app/Notifications/ApplicationReview.php, app/Notifications/ApplicationStatusChanged.php, app/Notifications/AtcSessionRecordedConfirmation.php, config/ipboard.php, config/mail.php, resources/views/adm/error/default.blade.php, resources/views/emails/default.blade.php, resources/views/emails/mship/account/welcome.blade.php, resources/views/emails/mship/security/reset_password.blade.php, resources/views/errors/default.blade.php, resources/views/slack/new.blade.php, resources/views/teamspeak/new.blade.php, resources/views/visit-transfer/admin/facility/create_or_update.blade.php
=> Update Links For Branding

resources/views/layout.blade.php, resources/views/mship/feedback/form.blade.php
For the time being, we are hiding the ability to submit feedback on Pilots until the PTD are ready to open the form.
=> Disable pilot feedback

resources/views/network-data/site/online.blade.php
Early 2017 has come and gone and other tasks have take priority over this.
=> Update Release Date Pilot Stats

resources/views/layout.blade.php
Lets enable pilots feedback for members.
=> Release Pilot Feedback

resources/views/layout.blade.php
Route to selection rather than form 1
=> Update feedback link

README.md, app/Console/Commands/NetworkData/ProcessNetworkData.php, app/Models/Airport.php, app/Models/Mship/Account.php, app/Models/NetworkData/Pilot.php, database/migrations/2017_08_20_013846_create_networkdata_pilots_table.php, database/migrations/2017_08_20_213819_create_airports_table.php
Data collection for pilot sessions.
=> Track pilot sessions / network data

resources/views/network-data/site/online.blade.php
Small change to ensure clarity on ATC online page.
=> Amend phrasing

app/Models/VisitTransfer/Application.php
Pass through the referee's account ID.
Closes #995
=> Hotfix: Fix V/T Referee Submission

app/Models/Mship/Concerns/HasMoodleAccount.php
=> Stop Banning Users on Moodle

resources/views/adm/layout.blade.php, resources/views/layout.blade.php
Add back in the mobile admin menu ability
Plus allow the admin icon/button to show on a small device
=> Fix & Tweak Styling

app/Http/Requests/VisitTransfer/ApplicationAcceptRequest.php, app/Models/VisitTransfer/Application.php, resources/views/visit-transfer/admin/application/view.blade.php
Make the application acceptance note optional. Also correct a typo.
Closes #1020
=> Remove note requirement on application acceptance

resources/assets/sass/app.scss, resources/views/mship/notification/list.blade.php
In the words of Calum, it has been made to "look prettier please"
Closes #1018
=> Re-Style Notifications Page

CONTRIBUTING.md
=> Update Contributing Guide With Latest Experiences

resources/assets/sass/app.scss, resources/views/visit-transfer/site/reference/complete.blade.php
Fixes the panel (makes it mobile-assessable). Also implemented some new, more colourful checkboxes.
Closes #1035
=> Fix Referee's Reference Content Panel

app/Http/Controllers/Adm/Mship/Feedback.php, resources/views/adm/mship/feedback/list.blade.php, resources/views/adm/mship/feedback/view.blade.php
Implements pagination on core admin feedback lists
Closes #1031
=> Implement feedback list pagination

resources/assets/sass/app.scss, resources/views/auth/login.blade.php
=> Add Secondary Auth Login Help

app/Exceptions/Community/AlreadyAGroupTierMemberException.php, app/Exceptions/Community/MustBeADivisionMemberException.php, app/Models/Mship/Concerns/HasCommunityGroups.php, tests/Unit/GroupMembershipTest.php
Fix namespace/path issues for community group tests
=> Fix community membership tests

app/Http/Controllers/Adm/Mship/Feedback.php, resources/views/adm/layout/sidebar.blade.php
1. Temporarily bypass an issue where the permissions system doesn't handle slugs properly with wildcards
2. Fix hard-coded feedback viewing authorisation
=> Some more feedback fixes

app/Console/Commands/TeamSpeak/TeamSpeakManager.php, app/Http/Controllers/TeamSpeak/Registration.php, app/Libraries/TeamSpeak.php
=> Teamspeak: Default channel idle time

app/Http/Controllers/VisitTransfer/Admin/Application.php, app/Http/Requests/VisitTransfer/ApplicationCompleteRequest.php, app/Models/VisitTransfer/Application.php, app/Policies/VisitTransfer/ApplicationPolicy.php, resources/views/visit-transfer/admin/application/view.blade.php, routes/web-admin.php
Implement a button to manually complete applications
=> Implement Complete Application Button

app/Libraries/TeamSpeak.php
=> Hotfix: Fix TS warning logic

resources/views/adm/mship/feedback/list.blade.php, resources/views/adm/mship/feedback/new.blade.php
Shows N/A for "Targeted Member" on non-targeted forms
Fixes #1106
=> Fix Submitter being shown in non-targeted feedback listing

app/Http/Controllers/Adm/Mship/Feedback.php
Makes permissions for feedback actioning dynamic
Fixes #1110
=> Bug Fix: Make Post Feedback Action permissions multi-form enabled

resources/views/visit-transfer/admin/application/view.blade.php
As requested by Barrie Joplin, change Complete button to another colour to distinguish from Accept button.
=> Change complete button colour

resources/views/layout.blade.php
Unrestricted the logout button from the vatsim-sso guard. Seemed to be causing issues on development builds using the demo sso.
=> Logout Button Visibility

CONTRIBUTING.md, ISSUE_TRACKING.md, README.md
This PR contains a number of docs updates in relation to the upcoming migration from GitHub Issues to JIRA.
=> CORE-33 Documentation Updates

app/Http/Controllers/Adm/Mship/Feedback.php, app/Http/Kernel.php, app/Http/Middleware/CheckAdminPermissions.php, routes/web.php
Change to .xlsx to ensure compatibility
=> Amend excel format

resources/views/fte/dashboard.blade.php
Button added.
Position of button signed off by Dan. Open to discussions though...
=> CORE-39 - Restart FTE Tour

app/Models/VisitTransfer/Application.php, app/Policies/VisitTransfer/ApplicationPolicy.php, resources/views/visit-transfer/site/application/view.blade.php, resources/views/visit-transfer/site/application/withdraw.blade.php
Allow users to withdraw VT applications that have been submitted. Resolves CORE-43
=> CORE-43 Withdraw Applications

app/Http/Controllers/Adm/Atc/Endorsement.php, app/Http/Controllers/Atc/EndorsementController.php, app/Models/Atc/Endorsement.php, database/migrations/2018_03_13_182129_add_endorsement_permission.php, resources/views/adm/atc/endorsement/check.blade.php, resources/views/adm/atc/endorsement/index.blade.php, resources/views/adm/layout/sidebar.blade.php, routes/web-admin.php
Implements an admin-side endorsement checker.
Closes CORE-47
=> CORE-47 Endorsement Admin

app/Http/Controllers/Smartcars/Api/Authentication.php
=> CORE-57 - Check for $account object

app/Models/Mship/Feedback/Answer.php
Prevents exception thrown on export
=> CORE-66 - Include soft deleted questions in model

composer.json, composer.lock
Resolves issue on v3.8.0 where TeamSpeak failing connection
Further investigation required to updated to latest package
=> Lock TeamSpeak Package

app/Http/Controllers/Mship/Feedback.php, tests/Feature/Mship/Feedback/FeedbackUserSearchTest.php
=> Prevent self feedback

tests/Feature/AdminMiddlewareTest.php
=> Admin Middleware Testing

resources/views/mship/feedback/form.blade.php
=> CORE-121 - Fix "next" button placement

.env.example, app/helpers.php, resources/assets/less/admin.less, resources/assets/sass/app.scss, resources/views/adm/layout.blade.php, resources/views/adm/mship/feedback/view.blade.php, resources/views/layout.blade.php
=> CORE-120 - Non-Production Environment Notification

tests/Feature/QuarterlyStatsTest.php
Just asserting successful loads
=> CORE-115 - Test Q Stats

app/Console/Commands/VisitTransfer/ApplicationsCleanup.php, database/factories/RefereeFactory.php, tests/Unit/VisitTransfer/ApplicationTest.php, tests/Unit/VisitTransfer/VisitTransferCleanupTest.php
=> CORE-150 V/T Cleanup Script

.travis.yml, Homestead.yaml.example, phpunit.xml
=> CORE-165 - PHPUnit Test Database

app/Http/Controllers/Site/HomePageController.php, resources/assets/sass/home.scss
`home.blade.php` available here: https://drive.google.com/file/d/1-CB6VHhTGAc2yPM42e-mOIUtWGSYfdaR/view?usp=sharing
=> CORE-173 / CORE-175 Dynamic Homepage/External Services

app/Http/Controllers/Site/HomePageController.php
`home.blade.php` available here: https://drive.google.com/file/d/1-CB6VHhTGAc2yPM42e-mOIUtWGSYfdaR/view?usp=sharing
=> CORE-174 Upcoming Event Banner

resources/views/visit-transfer/admin/facility/create_or_update.blade.php
=> CORE-188 - Remove Character

resources/assets/sass/_nav.scss, resources/assets/sass/app.scss, resources/views/components/nav.blade.php, resources/views/layout.blade.php
Restructure navbar to more conventional bootstrap format, and adjust breakingpoint
Closes CORE-184
=> CORE-184 - Navbar Overflow

resources/assets/sass/_nav.scss, resources/views/components/nav.blade.php
=> Hotfix: Fix core mobile navigation

app/Nova/Actions/Mship/BanAccount.php
=> FIX: Ensure BanAccountService is handled

resources/views/site/marketing/branding.blade.php
Updated a new forum thread URL on the branding guidelines page.
=> CORE-225 - Update URL for new forum thread

app/Http/Controllers/Adm/Mship/Account.php, resources/views/adm/mship/account/detail.blade.php
Loading data changes appears to be causing a large slow-down for loading account profiles. Also tidy up areas that are not implemented.
=> Improve Admin CP Performance

app/Http/Controllers/Adm/Mship/Feedback.php
Slugs are not supported via the generic URL check we are doing in admin middleware
=> Add Check For Viewing of Specific Form

app/Http/Controllers/TeamSpeak/Registration.php, resources/views/teamspeak/new.blade.php
Property of non-object exceptions being thrown on prod.
=> CORE-248 / 249 - TeamSpeak 500 Errors

resources/views/adm/mship/account/_ban.blade.php, resources/views/adm/mship/account/ban/index.blade.php
Typo issues from the mass replace of if statements to cans.
=> Fix Ban Button Conditional Displays

resources/views/site/atc/mentor.blade.php
Fixes Typo on "Becoming a Mentor" Page.
=> Fixes Typo on "Becoming a Mentor" Page

resources/views/site/atc/progression.blade.php
Updates the "Progression Guide" page. Deleted references to RTS system and pre-exams.
=> Updates the "Progression Guide" Page

resources/views/site/staff.blade.php
=> CORE-209 - Update Staff Page

resources/assets/sass/app.scss
=> CORE-251 - Fix cookie consent font

resources/lang/en/teamspeak.php
May consider use of routes in future...
=> CORE-253 - Update TeamSpeak URLs

resources/views/visit-transfer/admin/application/view.blade.php, tests/Feature/VisitTransfer/VisitTransferAdminTest.php
=> CORE-252 - VT Checks not showing

resources/views/visit-transfer/admin/facility/create_or_update.blade.php, resources/views/visit-transfer/admin/facility/list.blade.php
=> CORE-260 - V/T UI Bugs

app/Http/Controllers/Community/Membership.php, app/Policies/GroupPolicy.php, app/Policies/MembershipPolicy.php, app/Providers/AuthServiceProvider.php, tests/Feature/Community/DeploymentTest.php
=> CORE-298 - Authorising Community Deployment

app/Console/Commands/TeamSpeak/TeamSpeakCommand.php, app/Console/Commands/TeamSpeak/TeamSpeakManager.php
=> CORE-299 - TeamSpeak Server Group Exception

resources/views/site/staff.blade.php
As requested by DC - adds James Gibson to staff list.
=> Adds Development Flight Instructor to Staff

resources/views/site/atc/landing.blade.php
https://community.vatsim.uk/news/atc-training/egnx-training-aerodrome-update-r215/
=> Another NX change

composer.json, composer.lock, phpunit.xml
Add `codedungeon/phpunit-result-printer` to improve the look of PHPUnit.
Before:
After:
=> Add Pretty PHPUnit

app/Models/Mship/Concerns/HasForumAccount.php
=> CORE-318 - Fix community sync

resources/views/site/home.blade.php
Following experience with slightly less than helpful pilots.
=> Style: Useful Pilot Links - Front Page

app/Models/Mship/Feedback/Feedback.php, app/Nova/Feedback.php, app/Nova/Metrics/ActionedUnactionedFeedback.php, app/Nova/Metrics/TotalFeedback.php, app/Nova/Metrics/TotalFeedbackGraph.php, tests/Unit/Mship/Feedback/FeedbackModelTest.php
=> CORE-324 - Feedback Metrics

app/Models/Mship/Feedback/Feedback.php, app/Nova/Account.php, app/Nova/Actions/ActionFeedback.php, app/Nova/Actions/SendFeedback.php, app/Nova/Feedback.php, app/Nova/FeedbackResponse.php, app/Nova/Filters/FeedbackForm.php, app/Nova/Metrics/ActionedUnactionedFeedback.php, app/Nova/Metrics/TotalFeedback.php, app/Nova/Metrics/TotalFeedbackGraph.php, tests/Unit/Mship/Feedback/FeedbackModelTest.php
This is beautiful by the way. (Travis won't pass due to an ongoing issue)
=> CORE-255 - Viewing Membership Feedback

resources/views/site/atc/landing.blade.php, resources/views/site/staff.blade.php
As requested by DC.
Removes all references to Senior Division Instructors and updates the staff page.
=> Removes References to SDI's, Updates Staff Page

app/Http/Controllers/Auth/ResetPasswordController.php, tests/Feature/Mship/ResetPasswordTest.php
=> CORE-327 - Resetting Expired Password

app/Http/Controllers/Slack/Registration.php
Logs the SlackUserAdmin response when invite failed to allow debugging root cause.
=> Log Slack Errors

app/Nova/Aircraft.php
For reference, I've extracted all of the validation rules from the existing ones in the relevant controller. If they need to be amended feel free to suggest.
=> CORE-283 - FTE Aircraft Administration

app/Http/Controllers/Site/StaffPageController.php, resources/views/site/staff.blade.php
As per - https://community.vatsim.uk/news/united-kingdom/new-marketing-director-r246/  
Spoken to Loui and this is how he wants it formatting with the removal of Social Media Manager, until Marketing update has been posted.
=> Change of Marketing Director

app/Nova/Airport.php
Validation rules simply extracted from the existing controller.
=> CORE-282 - FTE Airports

app/Libraries/Storage/FteStorageWrapper.php, tests/Feature/FteCreationTest.php
=> Amend FTE Storage Wrapper

resources/views/site/staff.blade.php
As per https://community.vatsim.uk/news/united-kingdom/february-changes-r251/
=> Feb Changes to ATC and PTD Staff

app/Models/Mship/Account/Email.php, tests/Unit/Mship/MshipEmailTest.php
=> CORE-316 - Email Assignments

.gitignore, app/Http/Controllers/Adm/Smartcars/Resources/FlightController.php
=> CORE-351 - Fix FTE Updates

app/Console/Commands/NetworkData/ProcessNetworkData.php
=> CORE-356 - Network Data erroneous lat/longs

app/Http/Controllers/Adm/Mship/Account.php, resources/views/adm/mship/account/detail.blade.php, tests/Feature/Adm/AccountTest.php
=> CORE-354 - Admin 404 on non-member

app/Http/Controllers/Smartcars/Api/Flight.php
=> CORE-352 - FTE Posrep has no bid

app/Console/Commands/NetworkData/ProcessNetworkData.php
=> CORE-353 - Handle CERT downtime for network data

resources/views/site/staff.blade.php
On request by Loui Ringer to add Marketing Manager tag to the staff page.
=> Add Marketing Manager Vacancy On Staff Page

resources/views/site/staff.blade.php
https://community.vatsim.uk/news/marketing/appointment-marketing-managers-r255/
=> Add marketing managers

resources/views/site/staff.blade.php
The tag wasn't inserted at first commit - sorry.
=> Add 'Marketing Team' Tag

resources/views/adm/mship/account/detail.blade.php
Spatie/Laravel-Permissions doesn't support wildcard's at the moment
Closes CORE-346
=> CORE-346 - Detaching Roles on Adm

app/Libraries/TeamSpeak.php
=> CORE-362 - Duplicate Bot Connections

app/Http/Controllers/Smartcars/Api/Flight.php
=> CORE-363 - Fix FTE Invalid Bid

app/Libraries/Slack.php
Makes core set an array of attachments as per API spec.
=> Bug Fix: Slack API Attachments

app/Listeners/Smartcars/EvaluateFlightCriteria.php
Refactor (slightly messy) network time calculation to a protected method and put a check in place to stop divisions by 0.
=> CORE-355 - FTE Division By 0

resources/assets/sass/home.scss, resources/views/site/home.blade.php
=> CORE-367 - Login Link Not Showing On Mobile

app/Http/Controllers/Community/Membership.php, app/Policies/GroupPolicy.php, tests/Feature/Community/DeploymentTest.php
=> CORE-374 - Duplicate Community Memberships

app/Models/Training/WaitingListAccount.php, app/Nova/WaitingList.php, database/factories/SmartCars/SmartCarsFlightFactory.php, nova-components/WaitingListsManager/resources/js/components/Tool.vue, nova-components/WaitingListsManager/resources/js/eventBus.js, nova-components/WaitingListsManager/routes/api.php, nova-components/WaitingListsManager/src/Http/WaitingListsManagerController.php, nova-components/WaitingListsManager/src/ToolServiceProvider.php, nova-components/WaitingListsManager/src/WaitingListsManager.php, tests/Unit/Training/WaitingListAccountTest.php, tests/Unit/Training/WaitingListFlagTest.php
Pending demo to product owner.
=> CORE-387  - Waiting List 'Buckets'

app/Models/Training/WaitingList.php, app/Models/Training/WaitingListAccount.php, app/Nova/WaitingList.php, database/migrations/2018_07_20_085104_add_waiting_list_table.php, nova-components/WaitingListsManager/resources/js/components/TextInputModal.vue, nova-components/WaitingListsManager/resources/js/components/Tool.vue, nova-components/WaitingListsManager/resources/js/tool.js, nova-components/WaitingListsManager/src/Http/WaitingListAccountResource.php, nova-components/WaitingListsManager/src/Http/WaitingListNoteController.php, nova-components/WaitingListsManager/src/WaitingListsManager.php
Pending sign-off from DC & OR.
=> CORE-396 - Waiting List Notes - UI

resources/views/site/staff.blade.php
=> Staff Page Update

app/Http/Controllers/Atc/EndorsementController.php
- Fix method name
- Amend spelling of Endorsement
=> Endorsement Typos

routes/web-admin.php, tests/Feature/Admin/AccountTest.php
=> CORE-410 - User Impersonation Bugs

app/Nova/Actions/Training/AddFlagToWaitingList.php, app/Nova/WaitingList.php, app/Nova/WaitingListFlag.php, nova-components/WaitingListsManager/resources/js/components/Bucket.vue, nova-components/WaitingListsManager/resources/js/components/FlagIndicator.vue, nova-components/WaitingListsManager/resources/js/components/NoteIndicator.vue, nova-components/WaitingListsManager/resources/js/components/Tool.vue, nova-components/WaitingListsManager/resources/js/tool.js
Implements the usage of automated flags in the interface.
=> CORE-412 - Automated Flags in Interface

app/Libraries/TeamSpeak.php
=> CORE-411 - Teamspeak Controller Idle Exemption

app/Libraries/TeamSpeak.php, app/Models/Mship/Account.php, tests/Unit/Account/AccountModelTest.php, tests/Unit/TeamSpeakTest.php
=> CORE-409 - Duplicate Names on TS

database/factories/Mship/BanFactory.php, routes/web-admin.php, tests/Feature/Admin/AccountTest.php
=> CORE-414 - Incorrect Ban List Namespace

app/Console/Commands/ExternalServices/SyncCommunity.php
=> CORE-419 IPB Club Syncing

app/Http/Controllers/Adm/Smartcars/Resources/ExerciseController.php, app/Libraries/Storage/CoreUploadedFile.php, app/Libraries/Storage/FteStorageWrapper.php, app/Libraries/Storage/StorageWrapper.php, app/Models/Smartcars/Flight.php, tests/Feature/FTE/FteAdminTest.php, tests/Feature/FTE/FteCreationTest.php
Note, will require existing images to be move from public/storage/smartcars... to public/smartcars... 
Closes CORE-405 and CORE-417
=> CORE-405 / CORE-417 - FTE Image Uploading Bug Fixes

yarn.lock
Fixes some issues encountered on homestead deployments, and generally just installs newer versions of packages.
=> Yarn Package Version Upgrades

app/Http/Controllers/Mship/Notification.php, app/Models/Mship/Concerns/HasNotifications.php
=> CORE-420 - Duplication Notification Acceptance

resources/views/site/staff.blade.php
=> style: update web staff listing

resources/views/site/marketing/branding.blade.php
Fixes: https://helpdesk.vatsim.uk/scp/tickets.php?id=30777
=> WEB-612863: Update typography under branding guidelines to include DIN Alternate Regular

app/Http/Controllers/Api/CTS/ValidationsController.php, app/Http/Kernel.php, app/Models/Cts/Validation.php, app/Models/Cts/ValidationPosition.php, app/Repositories/Cts/ValidationPositionRepository.php, database/factories/Cts/ValidationFactory.php, database/factories/Cts/ValidationPositionFactory.php, resources/views/fte/exercise.blade.php, resources/views/site/airport/view.blade.php, routes/api.php, routes/web-public.php, tests/Database/MockCtsDatabase.php, tests/Feature/CTS/ValidationTest.php, tests/Feature/FTE/FTEWebInterfaceTest.php, tests/Unit/CTS/EventRepositoryTest.php, tests/Unit/CTS/ValidationPositionRepositoryTest.php
=> 1559 - JSON Feed for Validations

resources/views/site/staff.blade.php
Removal of 'George Barlow' following resignation. I just wanted to get this done to avoid confusion for the membership.
=> Update Web Staff Positions

app/Libraries/TeamSpeak.php, app/Models/Mship/Account.php, app/Providers/TelescopeServiceProvider.php, tests/Unit/Account/AccountModelTest.php
Introduces stricter name comparison on TS
Fixes #1602
=> Feature - Teamspeak Name Capitalisation

resources/views/site/staff.blade.php
Updated the staff page to reflect the new training department - Checked by Dan
=> Update staff page

composer.json, composer.lock
=> Fix - Laravel 6 Deployment

resources/views/adm/mship/account/_ban.blade.php
=> fix: add fallback for when banned_by is null in ban tab

app/Nova/WaitingList.php
As per;
https://github.com/laravel/nova-issues/issues/2308
https://github.com/laravel/nova-issues/issues/2221
=> Nova Bug For Action Auth

app/Nova/WaitingList.php, app/Policies/Training/WaitingListPolicy.php, database/migrations/2020_01_31_180100_add_waiting_list_action_permissions.php
Remove model specific authorisation whilst awaiting fix for Nova bug
=> Waiting List Permissions

app/Models/Training/WaitingList/WaitingListAccount.php, config/cache.php, tests/Unit/Training/WaitingList/WaitingListAccountTest.php
=> cache the result of the hour check

app/CloudflareHelper.php, composer.json
https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-
=> Cloudflare IP Helper

resources/views/site/home.blade.php
Here's a new Welcome for the Home Page. I am not sure if the line breaks are an issue - probably it will be rendered beautifully.
=> New Welcome Message Division Director

resources/views/site/staff.blade.php
Turns out I missed a spot. Updated to remove a former Marketing staff member
=> Style: Update Staff Page (again!)

resources/views/emails/mship/feedback/summary.blade.php
Removed route removed as part of migration of feedback to Nova.
=> Old Feedback Route Reference

tests/TestCase.php
As per docs at https://carbon.nesbot.com/docs/#api-testing
=> Set Testing Time Correctly

app/Models/Mship/Concerns/HasQualifications.php
=> Add Bugsnag Import

nova-components/WaitingListsManager/package.json, nova-components/WaitingListsManager/yarn.lock
=> bump laravel mix to v5 for waiting lists nova module

database/factories/ModelFactory.php
=> Fix: Add check to ensure unique qualification code in factory

app/Console/Kernel.php
- Re-order to make it a little easier to read
- Prevent overlapping on jobs likely to overlap (e.g. those running every minute)
=> Scheduler Amends

resources/views/site/staff.blade.php
- Adds in member services assistants
- Removes from previous roles
As per WEB-547102
=> Content: Staff Page Update

resources/views/site/operations/sectors.blade.php
Fixed some outdated frequencies, added some new ones to the tables
Corrected top-down order
=> Update frequencies on operations.sectors

resources/views/site/staff.blade.php
- Updates training staff as per #WEB-719395
=> style: Update Training Staff

resources/views/site/staff.blade.php
Corrected the DCRM's name, and centered some text I forgot to center last time
=> Style: Corrects staff member name, centers some more text

resources/views/emails/mship/account/welcome.blade.php
- Updates outdated links in the welcome email
=> Fix - Update Links in Welcome Email

resources/views/site/staff.blade.php
Reflect new TG restructure & new vacancies
=> Style: Reflect new staff changes

resources/views/site/staff.blade.php
https://community.vatsim.uk/news/united-kingdom/division-conflict-resolution-manager-r322/
=> Style: Updates DCRM

resources/views/site/staff.blade.php
https://community.vatsim.uk/news/united-kingdom/appointments-training-department-r323/
=> Training Staff Changes

.github/workflows/build_and_test.yml, composer.json, composer.lock, phpunit.xml
Commit messages should give a step-by-step of the changes made to make this work.
This PR is from my fork so should be sufficient as a proof of concept - it builds and passes without ever pulling Nova in or access to private tokens.
StyleCI can only run on our branches. If we merged something to master that did not comply with our rules, StyleCI would apply the fixed to master automatically.
=> Add Support For GitHub Actions On Forks

app/Console/Kernel.php
Redis should be able to handle this.
Closes #1604
=> Re-Enable TG Forum Sync

config/horizon.php
Amends the name of the queue for the config
=> Queue Wait Time Threshold

database/migrations/2020_06_13_171913_add_missing_primary_keys.php
In preparation for MySQL 8 upgrade
=> Missing Primary Keys

resources/views/site/atc/landing.blade.php, resources/views/site/atc/mentor.blade.php, resources/views/site/pilots/landing.blade.php
Fixes #1817 
- Fixed outdated references to TGs
- Some other content changes 
- Formatting updates
=> Training pages text updates

app/Libraries/TeamSpeak.php
=> 1831 - Define $factory For TeamSpeak Library

app/Http/Controllers/Smartcars/Api/Flight.php
=> 1833 - Check For $bids Before Checking Count

resources/views/mship/feedback/form.blade.php
=> 1838 - Turn Autocomplete Off On Feedback Forms

tests/Feature/Account/EmailAssignmentTest.php
=> Fix Secondary Email Test

resources/views/site/operations/sectors.blade.php
Adds LON_D_CTR to top down coverage for LL, LC, MC, KB & MD
Corrects spelling of Teesside
=> Updates sector page

config/database.php
=> 1854 - Redis Timeout Change

app/Http/Controllers/Mship/Feedback.php
=> Allow For Special Characters In Feedback Search

app/Http/Controllers/Api/OAuthUserController.php
Prime candidate for a git blame on my typo!
=> API Exception For ATC Qualification

app/Http/Controllers/Discord/Registration.php, resources/views/mship/management/dashboard.blade.php
Remove dependency on `discordbeta` permission to register for Discord.
=> Release Discord

tests/Feature/Services/DiscordTest.php
Now that beta has been removed.
=> Enable Discord Test

app/Http/Controllers/Mship/Feedback.php, app/Jobs/Mship/SyncToCTS.php, app/Jobs/Mship/SyncToForums.php, app/Jobs/Mship/SyncToHelpdesk.php, app/Jobs/Mship/SyncToMoodle.php, app/Jobs/UpdateMember.php, config/horizon.php, tests/Feature/Account/Feedback/FeedbackUserSearchTest.php
- Creates new `user_sync` queue on which CERT Update jobs and Syncing to external services are performed
- Sets number of tries on rate-limited UpdateMember job to prevent job aborting after one attempt
=> Fix - Implement User Sync Queue

app/Models/Mship/Qualification.php
Ensure people that have the P0 if they also have another rating.
=> Add P Ratings To Array

resources/views/site/staff.blade.php
=> Updates VFR Flight Instructor

resources/views/components/nav.blade.php, routes/web-public.php
=> 1925 - Remove Progression Guide Route

resources/views/site/pilots/landing.blade.php
=> Updates pilot training landing page

app/Console/Commands/ExternalServices/SyncCommunity.php
Use the name attribute to sync names to forum (will then account for nickname being set).
=> Community Name Sync

resources/views/site/staff.blade.php
=> style: remove DCRM from staff page

app/Http/Controllers/Adm/Smartcars/Resources/AirportController.php
=> fix: Unable to update existing FTE airport

resources/views/site/atc/newcontroller.blade.php
Fixes issue flagged on discord:
https://media.discordapp.net/attachments/745969064114913320/766286319746809896/image0.png?width=418&height=905
=> fix: Make image responsive

app/Http/Controllers/Site/StaffPageController.php, resources/views/site/staff.blade.php
Updates Ops Staff:
- Adds Jack Edwards
- Adds Enroute, Aerodrome and Sector File Coordinator roles
=> style: Update operations staff

app/Models/Mship/Concerns/HasForumAccount.php
We removed community groups in #1885 so I am surprised this hasn't blown up yet.
=> Remove Community Groups & Clubs From Forum Sync

resources/views/site/atc/newcontroller.blade.php
As per https://trello.com/c/FYuyJ09b
=> New TGNC Airports

app/Console/Kernel.php
=> Disable Secondary Forum Group Sync

app/Http/Controllers/Site/AirportController.php, composer.json, composer.lock, resources/views/site/airport/view.blade.php
Upgrades the stand status package to use version 2 (which should stop some of the errors we are seeing in production).
=> Update Stand Status

app/Http/Controllers/VisitTransfer/Site/Application.php, app/Http/Controllers/VisitTransfer/Site/Dashboard.php, app/Http/Controllers/VisitTransfer/Site/Reference.php
This adds page titles to the visit/transfer process, as referenced in [Discord](https://discord.com/channels/705488311346790471/705813486885666928/796704988860383283)
=> style: Visit/transfer process page titles

.github/workflows/deploy.yml
Simple format string fix to use correct positional numbers.
=> Actions: Fix Discord failure notification

config/services.php
As per https://discord.com/developers/docs/reference#api-reference
=> Fix - Update Default Discord API URL

resources/views/site/airport/view.blade.php
At the rest of ops, this PR hides;
-Nav-aids
-Runways
-ATC stations
-SIDs
-STARs
=> Hide Airfield Info Attributes

resources/views/mship/management/dashboard.blade.php
Rebalances the two columns by moving email address from right to left, under personal details. Left column personal details, right column API's etc.
=> Update mship dashboard

app/Console/Commands/Members/UpdateActiveDivisionMembers.php, app/Console/Kernel.php
Not too sure what we should limit this job to by default - what do you think @CalumTowers?
=> feat: Sync Division Members Daily

resources/views/site/community/vt-guide.blade.php, resources/views/site/join.blade.php
=> Fix Broken Links

resources/views/site/atc/bookings.blade.php, resources/views/site/operations/sectors.blade.php
Amendes the booking guidance on /atc/bookings to reflect restrictions on London/Gatwick (EGKK)
=> Style : New bookings rules

resources/views/site/staff.blade.php
Removed Charlie, added Kieron.
=> Update APP Instructor

app/Console/Kernel.php
Shifting some of the scheduler timings to try and reduce throughput and spread load across hours (rather than concentrated)
=> Scheduler Timing Changes

app/Http/Controllers/Mship/Management.php
Having recently used the cache for something else, I release now that the Cache TTL operates in seconds rather than ms.
Therefore this is currently 1000 hours!
Changed to 60 seconds * 60 i.e. an actual hour!
=> fix: Cert Request Check Cooldown

app/Console/Commands/NetworkData/ProcessNetworkData.php
Download network data in the handler.
Otherwise, we are downloading the network datafile every time we run a command (Also if that datafile goes down, it would block us running commands!)
=> fix: Process Network Data Handler

resources/views/site/operations/sectors.blade.php
Various changes/additions to top-down list on sectors page of the website to reflect changes to everyday sectors in LAC North
=> Updated airfield top-down info to reflect changes in LAC North

app/Models/Mship/Concerns/HasCTSAccount.php
- Adds check for states to create
- Fixes a null joined date column error
- Uses more concice method of getting preferred name
=> fix: Various CTS syncing fixes

app/Events/VisitTransfer/ApplicationCancelled.php, app/Exceptions/VisitTransfer/Application/ApplicationNotAcceptedException.php, app/Http/Controllers/Adm/VisitTransfer/Application.php, app/Http/Requests/VisitTransfer/ApplicationCancelRequest.php, app/Http/Requests/VisitTransfer/ApplicationRejectRequest.php, app/Models/VisitTransfer/Application.php, app/Policies/VisitTransfer/ApplicationPolicy.php, app/Providers/EventServiceProvider.php, database/factories/ApplicationFactory.php, resources/views/visit-transfer/admin/application/view.blade.php, resources/views/visit-transfer/emails/applicant/status_changed.blade.php, routes/web-admin.php, tests/Feature/VisitTransfer/AdminTest.php, tests/Unit/VisitTransfer/ApplicationPolicyTest.php, tests/Unit/VisitTransfer/ApplicationTest.php
- Implement ability to cancel an accepted application
- Modify policy requirements to accept, reject and complete applications
=> feat: Improved Visit/Transfer workflows

app/Http/Controllers/Atc/EndorsementController.php, app/Http/Controllers/Site/HomePageController.php
=> fix: Exception on endorsement check page with no qualification

app/Http/Controllers/Mship/WaitingLists.php, resources/views/mship/waiting-lists/index.blade.php
Adds message for OBS controllers telling them that the OBS->S1 waiting list won't show
=> style: OBS waiting list clarification

resources/views/site/community/terms.blade.php
Updates T+Cs to 2022 version; retains previous version until transition - after which this can be removed.
=> Style: Update T+Cs

resources/views/site/staff.blade.php
Per https://trello.com/c/2X0KSL1J/252-pt-staff-website-update
=> style: Staff Change - new VFR FI

app/Libraries/UKCP.php
Needs: https://github.com/VATSIM-UK/uk-controller-api/pull/956
=> Update UKCP API routes

app/Console/Commands/Members/SyncCtsRoles.php, app/Models/Cts/PositionValidation.php, app/Repositories/Cts/StudentRepository.php, database/migrations/2022_08_11_165740_add_gatwick_students_role.php
=> feat: add gatwick student sync role + permission

resources/views/site/operations/sectors.blade.php
Added new secondary position SCO_WD_CTR for the purposes of controller bookings
=> style: Added new secondary position (SCO_WD)

app/Http/Controllers/Adm/VisitTransfer/Application.php, app/Http/Controllers/Adm/VisitTransfer/Reference.php, app/Models/Traits/HasStatus.php, app/Models/VisitTransfer/Application.php, app/Models/VisitTransfer/Reference.php
- Previous logic dictated that if a reference was under pending, it would try to accept when the application is accepted. However, a reference can only be accepted if it has been submitted.
- This logic has been fixed to operate correctly (accept if submitted, cancel if not submitted)
=> fix: Pending references preventing accepting application

resources/views/site/atc/endorsements.blade.php
- Changed column format so it should look/feel slightly more intuitive to navigate on all devices
- Re-ordered to reflect rating required
- Added font awesome icons
- Updated formatting (lots of `<p>`)
- Updated Gatwick movement stats
- **No** changes have been made to any of the requirements or guidance
=> style: endorsements page updated

resources/views/site/operations/sectors.blade.php
- Added VATGlasses link
- Updated text to be more readable
- Updated military frequencies and callsigns
=> style: Simplified and updated ops sectors page

resources/views/site/atc/endorsements.blade.php
=> style: Added details of Shanwick Oceanic endorsement

resources/views/site/community/teamspeak.blade.php, resources/views/site/community/vt-guide.blade.php, resources/views/site/join.blade.php, resources/views/site/pilots/oceanic.blade.php
Hi, 
These changes update outdated links across the site.
=> Update various links

app/Events/Mship/AccountAltered.php, app/Listeners/Training/WaitingList/CheckWaitingListAccountInactivity.php, app/Listeners/Training/WaitingList/CheckWaitingListAccountMshipState.php, app/Providers/EventServiceProvider.php, config/app.php, tests/Feature/Training/WaitingListInactivityIntegrationTest.php, tests/Unit/Account/Sync/AccountAlteredEventTest.php, tests/Unit/Training/WaitingList/WaitingListAccountStateChangeTest.php
Adds various changes to add a dryRun mode for the listeners which react
to state changes.
=> refactor: add dryRun and add integration tests for automated removals

resources/views/site/staff.blade.php
Add Developer Dave Etheridge to Core Staff Page
=> Added Dave Etheridge to core staff page

resources/views/site/staff.blade.php
Adds Ben Esen to the staff page
=> Adds Ben Esen to staff page

app/Http/Controllers/Site/StaffPageController.php, resources/views/site/staff.blade.php
Change Member Services Director to John Batten
=> Update staff page for Member Services Director

resources/views/site/staff.blade.php
Alphabetise the Web Team developers on the staff page
=> refactor: alphabetise Developers on staff page

resources/views/site/community/vt-guide.blade.php
VT applications are opening for Enroute controllers.
This pull request updates the disclaimer in the VT guide to represent this.
=> VT enroute open vt-guide update

resources/views/visit-transfer/emails/applicant/status_changed.blade.php
refactor: update visitor application acceptance message. 
Message content from John Batten
=> refactor: Update visitor application acceptance message

resources/views/site/staff.blade.php
Updated Operations staff names/roles April 2023
=> Operations Team Updates

app/Events/Mship/AccountAltered.php, app/Listeners/Training/WaitingList/CheckWaitingListAccountInactivity.php, app/Listeners/Training/WaitingList/CheckWaitingListAccountMshipState.php, app/Notifications/Training/RemovedFromWaitingListInactiveAccount.php, app/Notifications/Training/RemovedFromWaitingListNonHomeMember.php, config/app.php, tests/Feature/Account/WaitingListsTest.php, tests/Feature/Training/WaitingListInactivityIntegrationTest.php, tests/Unit/Training/WaitingList/WaitingListAccountStateChangeTest.php
Also removes now redundant dry-run flag.
=> feat: route notifications for inactive waiting lists accounts to discord

resources/views/site/atc/heathrow.blade.php
Spelling mistake and rewording of Get Started section
=> Refactor/changes to Heathrow page Get started section

app/Console/Commands/Members/SyncCtsRoles.php, app/Models/Cts/ValidationPosition.php
Split from the role rules PR to get this in first
=> feat: Shanwick Syncing

database/migrations/2023_05_14_102302_add_pilot_instructor_ratings.php
Ticket: https://linear.app/vatsimuk/issue/WEB-117/support-new-pilot-ratings
=> feat: support FI and FE pilot ratings

resources/views/site/staff.blade.php
Staff page updates adding Craig Stewart as Training Department Assistant and Will Hinshaw as Lead Mentor (TWR)
=> refactor : Add Will Hinshaw and Craig Stewart to Training Department Staff list

resources/views/ukcp/token/guide.blade.php
Updates the UKCP setup guide for the recent changes to credentials.
=> Update UKCP setup guide

app/Libraries/UKCP.php, tests/Unit/UKCPLibraryTest.php
=> fix: increase ukcp stand status request timeout

app/Jobs/Mship/SyncToDiscord.php, app/Libraries/Discord.php, app/Providers/AppServiceProvider.php
https://discord.com/developers/docs/topics/rate-limits
=> refactor: better handle discord rate limiting & limit to only one try at a time

app/Jobs/UpdateMember.php, app/Models/Mship/Account.php, app/Models/Mship/Concerns/HasQualifications.php, app/Models/Mship/Qualification.php, database/migrations/2023_06_07_184051_add_military_pilot_ratings.php, resources/views/mship/management/dashboard.blade.php, tests/Unit/Account/AccountModelTest.php, tests/Unit/Mship/MilitaryPilotQualificationDetectionTest.php
- Revert "fix: bad method name in UpdateMember due to alias (#3102)"
- Revert "revert: military piot ratings (#3103)"
- fix: military ratings returned as proper typed array
=> feat: military pilot ratings

app/Models/Mship/Account.php, composer.json, composer.lock, config/filament.php, database/migrations/2023_06_24_150343_add_admin_beta_permission.php, tests/Unit/Account/Filament/FilamentAccessTest.php
Not waiting for me to finish the waiting list refactor.
=> chore: scaffold laravel filament admin panel package

app/Jobs/Mship/SyncToDiscord.php, app/Libraries/Discord.php, app/Providers/AppServiceProvider.php
This reverts commit 569b40b881bbbe4e8677e38c119be249b63d42dd.
=> refactor: reinstate discord rate limiting changes rollback

resources/views/site/staff.blade.php
- Operations appointments
- Pilot Training departures
=> Staff updates

resources/views/site/operations/sectors.blade.php
Per https://community.vatsim.uk/topic/39092-2023-12-28-aerodromes-egllssgwnxbbtktc-changes-to-coordination-procedures-due-to-tc-midlands-implementation/
Added EGTC and EGTK to top-down order list
Added TC Mids to who to call
=> Add TC Mids to top down order

config/services.php, resources/views/site/airport/view.blade.php
NB: API token needs to be changed in environment for deployment
=> feat: ChartFox v2 API

resources/views/site/staff.blade.php
Still required: picture for the Member Services Director in app\Http\Controllers\Site\StaffPageController.php
=> staff page updates

app/Models/Atc/PositionGroup.php, app/Models/Atc/PositionGroupPosition.php, app/Models/Roster.php, tests/Unit/Roster/AccountCanControlTest.php
- **fix: correctly determine if account can control when position in multiple position groups**
- **more tests for negative cases**
=> fix: more roster tests & support position contained in multiple position groups

.devcontainer/devcontainer.json, app/Livewire/Roster/Show.php, database/seeders/Testing/PositionsAndEndorsementsSeeder.php, resources/views/components/layouts/app.blade.php, resources/views/livewire/roster/show.blade.php, tests/Feature/Roster/ShowTest.php
Overflow behaviour
Closes TECH-239
=> feat: Roster Wildcard Search

app/Http/Controllers/Site/StaffPageController.php, resources/views/site/staff.blade.php
=> July 2024 staff changes

resources/views/site/staff.blade.php
=> Ops Director resignation

app/Http/Controllers/Site/StaffPageController.php, resources/views/site/staff.blade.php
In coordination with BW and DW.
Added recent and overdue changes.
=> Update staff page (#3854)

app/Console/Commands/Roster/UpdateRoster.php, app/Filament/Pages/Operations/GenerateQuarterlyStats.php, app/Filament/Resources/RosterUpdateResource.php, app/Filament/Resources/RosterUpdates/Pages/ListRosterUpdates.php, app/Filament/Resources/RosterUpdates/Pages/ViewRosterUpdate.php, app/Models/Roster.php, app/Models/RosterHistory.php, app/Models/RosterUpdate.php, app/Policies/RosterUpdatePolicy.php, database/migrations/2025_01_07_114512_create_roster_updates_table.php, database/migrations/2025_01_07_120305_add_roster_update_id_to_roster_history.php, tests/Database/MockCtsDatabase.php
- Adds stats to quarterly stats for ATC related information
- Adds logging of roster updates and key stats on each run, which are in turn displayed in admin
Resolves TECH-310
Resolves TECH-261
=> Improved Stats

.devcontainer/devcontainer.json, .devcontainer/initialSetup.sh, config/services.php, resources/views/components/nav.blade.php, resources/views/site/home.blade.php
Adds suggestions for nav improvements.
Also fixes some initial devcontainer setup errors
=> feat: Homepage Nav Update

app/Filament/Resources/AccountResource/RelationManagers/EndorsementsRelationManager.php, database/migrations/2025_03_26_184253_add_virtual_duration_column_to_mship_account_endorsements.php
- Groups by endorsement type
- Allows filtering by endorsement type
- Shows duration in days at endorsement and endorsement type level
=> TECH-283: Improve endorsements page on account profile

resources/views/site/operations/markdown/arrivinguk.blade.php, resources/views/site/operations/markdown/controller.blade.php, resources/views/site/operations/markdown/departinguk.blade.php, resources/views/site/operations/markdown/military.blade.php, resources/views/site/operations/markdown/ukareasectors.blade.php, resources/views/site/operations/markdown/vatglasses.blade.php, resources/views/site/operations/markdown/vfr.blade.php, resources/views/site/operations/sectors.blade.php
- Created Markdown Folder within resources/site/operations
- Converted all of the sections to Markdown
- Modified sectors.blade.php to pull from the markdown folder while retaining previous functionality
Resolves issue #4071
=> Convert OPS/Sectors to Markdown

resources/views/site/atc/newcontroller-process.blade.php, resources/views/site/pilots/landing.blade.php
- Updated the wording on the Landing page
- Linked to waiting list
- Updated the new controller-process to use the routing rather than hard link to waiting list
=> Fix: Pilot waiting list

resources/views/site/atc/heathrow-faqs.blade.php, resources/views/site/atc/newcontroller-panel.blade.php, resources/views/site/atc/newcontroller.blade.php
Fixes #4152
Per issue, updated in the 3 places I could find it.
Hopefully I haven't missed any instances and this works as I can't build core :(
=> TECH-377: Issue #4152 - Update UK Controller Pack Links

resources/views/site/atc/newcontroller-panel.blade.php
Added links for correct version of euroscope and updated the link for the pack instal readme
=> Update links for euroscope

app/Filament/Resources/FeedbackResource.php
Fixes #4178
Added ```Feedback Type``` column
Made ```Feedback Type``` column sortable
=> Fixes #4178 - Add feedback form i.e. feedback type to feedback admin panel

resources/views/site/staff.blade.php
Removal of @atoff and added @kristiankunc 
[Departure Message](https://discord.com/channels/705488311346790471/705813598580244532/1391827725291094177)
[Appointment message](https://discord.com/channels/705488311346790471/705813598580244532/1389301281923010704)
=> Tech team departure and Appointment

resources/views/discord/new.blade.php, resources/views/mship/management/dashboard.blade.php
Fixes #4256
Removed discord discriminators
=> Fixes #4256 - Stop displaying Discord discriminators

.github/dependabot.yml
Groups vite dependabot updates together
=> Add vite stack dependabot group

app/Filament/Admin/Resources/AccountResource.php, app/Filament/Admin/Resources/AccountResource/RelationManagers/WaitingListsRelationManager.php
Added new relation manager for waiting list accounts
=> Show waiting lists on account page
