app/Modules/Community/Policies/MembershipPolicy.php

When members were trying to go back and join another region-based community, after selecting UK ONLY, they were told it was unauthorised.  Resolved by removing the default group from the count.

Allow members to join region, if part of UK

---

resources/views/mship/management/dashboard.blade.php

Fixes #736 - Rating dates were not displaying correctly for Pilot Ratings in the tooltip.
Error for no Pilot ratings was also worded towards ATC - resolved here.

Fixes #736 - Pilot Ratings Tooltip

---

CONTRIBUTING.md

Added comment on running module migrations to remove "table doesn't exist" errors for new installations

Update Contributing Doc to include module migrations

---

app/Models/Mship/Account.php
app/Modules/Visittransfer/Resources/Views/site/reference/_layout.blade.php

The sorting function currently is use throws a uasort() error (when the referee has multiple reference requests) as, even though it may be unmodified, if it is run through any debug function, it thinks it has been. It is a documented PHP bug.
Fixed that by using the sortBy function over sort, which produces the same results as if the code before had been used and worked.
Also, whilst investigating, found that if a referee has multiple reference requests, the applications are shown incorrectly in the "Pending Applications", as it only used the application that the referee was currently visiting to populate the foreach().
This fixes #750

Hotfix: Fixing V/T error from multiple reference requests

---

resources/assets/sass/app.scss
resources/views/mship/management/dashboard.blade.php

Added a new CSS class so that columns can, where necessary, break the text to fit within their bounds.
Implemented into the dashboard where needed (Community groups, TeamSpeak registrations and account qualifications).
**Gulp will need to be run on deployment**
Closes #655

Overlapping texts

---

app/Http/Controllers/Slack/Registration.php

* Checks tokens based on if they've expired or not.
* Fixed message stating "used but not linked" to is_used, rather than is_expired.
Fixes #779

Fixes #779 - Check the validity of slack tokens when generating

---

app/Modules/Visittransfer/Http/Controllers/Site/Application.php

Re-arranged the order of `postRefereeDelete`'s parameters so that the `$reference` is in the right place (and converted to a model correctly) 
Closes #841

Hotfix: Error when trying to delete reference (referee)

---

app/Http/Controllers/Adm/Mship/Account.php

Notes added via ACP where not being assigned their correct note type. This is because of the following logic:
`
if (is_object($noteType) && $noteType->exists) {
$noteType = $noteType->getKey();
} else {
$noteType = Type::isDefault()->first()->getKey();
}
` from Models\Mship\Account@Line 1117
If a note type object is not passed, then it will default to system generated. In this case, the function was being sent an integer (the ID of the note type), and not the object.
Closes #855

Fix note not being assigned correct type

---

app/Modules/Visittransfer/Http/Requests/ApplicationRefereeAddRequest.php

There was a slight bug where the state used for comparison against the referee's was selected with `->primary_state` and not `->primary_permanent_state`, as is needed to ensure that temp states are not considered.
Closes #870

Fix V/T "referee not in region"

---

resources/assets/css/AdminLTE/AdminLTE.css
resources/views/adm/layout.blade.php

1) Address issue #420 : Added in the sidebar toggle button, which will only be visible in the view widths where the sidebar is hidden. When clicked, it shows the sidebar, and again to close it.
2) Address some styling issues found:
In the SM stage, the "logo" section seems to continue the style that it had when the sidebar was below it. But, however, this sidebar is no longer there in the SM stage, and therefore it looks out of place:
Turned into this:
Closes #420

Add admin mobile menu ability (+ fix some styling)

---

app/Console/Commands/TestEmails.php
app/Events/VisitTransfer/ReferenceCancelled.php
app/Http/Controllers/VisitTransfer/Site/Reference.php
app/Listeners/VisitTransfer/NotifyApplicantOfReferenceCancellation.php
app/Listeners/VisitTransfer/NotifyApplicantOfStatusChange.php
app/Listeners/VisitTransfer/NotifyRefereeOfReferenceDeletion.php
app/Models/VisitTransfer/Reference.php
app/Notifications/ApplicationReferenceNoLongerNeeded.php
app/Providers/EventServiceProvider.php
resources/views/adm/mship/account/_note.blade.php
resources/views/visit-transfer/emails/applicant/reference_cancelled.blade.php
resources/views/visit-transfer/emails/reference/request.blade.php
resources/views/visit-transfer/site/reference/complete.blade.php
routes/web-main.php

Gives referees an option at the start of the online form to mark that they do not know the applicant.
Once clicked, the application is moved to Under Review, the community is notified and the reference is marked as "Cancelled".
(Have also decided to pull #937 into here as it is slightly related)
Closes #565

Allow referees to state they do not know the applicant

---

app/Http/Controllers/Mship/Feedback.php
database/migrations/2017_03_31_211222_create_feedback_tables.php
database/migrations/2017_07_01_152542_make_userid_input_placeholder_grammatically_correct.php
resources/views/mship/feedback/form.blade.php
routes/web-main.php

Adds in a search button to allow searching for members. Once clicked, the selected member's CID will be automatically placed into the correct form field.
Worth mentioning that the exact name of the user they want to find is not required, and it will try to find a match from our database.
Also fix a small grammatical error in the feedback migration

Member search in ATC/Pilot feedback forms

---

resources/views/mship/management/dashboard.blade.php

Add a small message to notify users on how they can change their primary email, and how long it takes for it to come through.

Add Primary Email Tooltip

---

app/Http/Controllers/Adm/Mship/Account.php

Account being used for the ban notification was the current user, instead of the person being banned
Fixes #988

Fix Ban Email Recipient

---

app/Http/Controllers/Adm/Mship/Feedback.php

Add in check to see if the user has the form-specific list permission
(This was stopping people who only had pilot or only had ATC list permissions from accessing the list)

Hotfix: Feedback List Perms

---

app/Http/Controllers/Adm/Mship/Account.php
database/migrations/2017_10_27_184914_add_adm_usr_detail_feedback_perm.php
resources/views/adm/mship/account/detail.blade.php

1. Implement the feedback received list in Adm/Mship (Was their previously, but forgot permission - perm will need to be given to the relevant roles once live. Will give access to ALL targeted feedback on the member)
2. Adds new V/T tab in user profile, listing all previous and current V/T applications
Closes #994 and #931

New Admin Info Tabs: V/T & Feedback

---

app/Http/Controllers/Adm/Mship/Account.php

Some ban emails where being sent to the incorrect person (the banner) rather than the recipient of the ban.
Closes #1027

Hotfix: Fix some ban emails going to the incorrect account

---

app/Http/Controllers/Adm/Mship/Feedback.php
app/Http/Controllers/Mship/Feedback.php
app/Http/Requests/Mship/Feedback/NewFeedbackFormRequest.php
app/Models/Mship/Feedback/Form.php
app/Notifications/Mship/FeedbackReceived.php
app/Notifications/Mship/FeedbackSummary.php
app/Providers/EventServiceProvider.php
database/migrations/2017_11_21_192224_fix_feedback_optional_questions.php
resources/views/adm/layout/sidebar.blade.php
resources/views/adm/mship/feedback/new.blade.php
resources/views/adm/mship/feedback/settings.blade.php
resources/views/emails/mship/feedback/new_feedback.blade.php
resources/views/emails/mship/feedback/summary.blade.php
resources/views/mship/feedback/form.blade.php
routes/web-admin.php

1. Fix a bug where if an optional field was not filled in, there would be an SQL error
2. Add a form "visibility" attribute. Determines whether the form will display on the list found on core > feedback
3. Configure mship form links to use the forms slug, rather than the ID
4. Fix some issues where targeted vs non-targeted forms where being treated incorrectly

Numerous Feedback Fixes

---

resources/views/layout.blade.php
resources/views/visit-transfer/site/dashboard.blade.php

Adds in a small check to see if the token actual exists before trying to display it. Does not fix the actual issue (#1023) because that it on hold until CERT v2, but this will do in the meantime so that people can still access V/T.
Also fixed a small oversight in having two logout buttons from previous PR...

Temporary fix for deleted reference tokens

---

app/Models/Mship/Role.php

Utilise regex to search for alphanumeric slugs. Will be redone later on during review of permissions logic and utilising policies, but until then this will suffice.

Hotfix: Accommodate slugs in permissions

---

app/Console/Commands/VisitTransfer/ApplicationsCleanup.php
app/Http/Controllers/Smartcars/Api/Flight.php
app/Http/Controllers/Smartcars/Api/Pirep.php
app/Models/VisitTransfer/Application.php
database/migrations/2018_03_07_194806_fix_teamspeak_foreign_keys.php
resources/views/visit-transfer/admin/application/view.blade.php

Resolves:
CORE-38 - Remove incorrect TeamSpeak foreign key
CORE-51 - Fix issue searching PIREPs for those with a specific departure/arrival ID
CORE-52 - Fix smartCARS POSREPs using commas instead of periods in their lat/lons.
CORE-53 - Fix displaying of VT applications where a user's previous rating is unknown.
CORE-56 - Lapse VT applications with expired referees.

Hotfix 3.6.5

---

app/Console/Commands/Members/ImportMembers.php

Fixes regression from 79b6b533, where members are currently being updated if their email matches the one in CERT, rather than if it does not.

Hotfix 3.6.6 - Fix Importing Member Emails

---

app/Listeners/Smartcars/EvaluateFlightCriteria.php

**Strongly suggest a review of #1159 first.**
- `$pirepTime` the time logged on the PIREP (smartCARS only logs airborne time) in HH:MM:SS format.
- `$networkTime` pulls any records of that user being connected to VATSIM as a Pilot between the first and last posrep received from smartCars for this flight.
- Checks whether `$networkTime` is at least 90% of `$pirepTime` and marks as failed if it is not.
Not really hugely happy with...
- DB query just thrown in the middle
- Looks a bit messy all within the listener
Happy to take any suggestions about whether this logic would be better in its own function.

CORE-41 - FTE Network Check

---

app/Http/Controllers/VisitTransfer/Site/Reference.php
app/Listeners/VisitTransfer/NotifyCommunityOfUnderReviewApplication.php
app/Listeners/VisitTransfer/NotifyRefereeOfReferenceCancellation.php
app/Models/VisitTransfer/Application.php
app/Models/VisitTransfer/Reference.php
app/Notifications/ApplicationReferenceCancelledByReferee.php
app/Providers/EventServiceProvider.php
resources/assets/less/admin.less
resources/views/visit-transfer/admin/application/view.blade.php
resources/views/visit-transfer/emails/applicant/_layout.blade.php
resources/views/visit-transfer/emails/applicant/status_changed.blade.php
resources/views/visit-transfer/emails/reference/reference_not_required.blade.php

Fixed logic that deletes references & notifies referees. Once the application is withdrawn or expired, the reference and its access tokens are deleted, and the referee is emailed.
Closed CORE-55

CORE-55 - Referee notification

---

app/Console/Commands/ExternalServices/ManageSlack.php

Automatically registers a slack user when their slack email address matches a core accounts primary or secondary emails.

CORE-37 - Automatic Slack Registration

---

config/debugbar.php

This is really helpful for identifying where duplicated queries are coming from.

Enable Debugbar Backtrace

---

app/Libraries/TeamSpeak.php

Teamspeak bot now kicks the locally banned client then waits 2 seconds before then going ahead with banning them.

CORE-185 Update Teamspeak Bot Local Ban Handling

---

routes/web-admin.php

At present, users visiting `/adm` will be redirected to the user dashboard rather than the adm dashboard.
https://vatsimuk.atlassian.net/browse/CORE-210

CORE-210 - Adm Redirect

---

app/Http/Controllers/Slack/Registration.php
app/Providers/AuthServiceProvider.php
app/helpers.php
tests/Feature/Mship/SlackFeatureTest.php

Improves error message displayed when an existing slack registration is found. Resolves CORE-207.

CORE-207 - Existing Slack Registration Error Message

---

.gitignore

As CORE-171 is a long way off, I'm fed up of checking out branches being slow due to nova files.

Ignore nova on upstream branches

---

resources/views/site/community/vt-guide.blade.php

Update link to follow dynamic linking (broken with new subdomain change)

Fix link for visiting

---

resources/views/site/home.blade.php

Return hours appended to 0 instead of minutes. Was returning crazy figures - 029:29:43

Correct UTC Timestamp

---

resources/views/visit-transfer/admin/facility/create_or_update.blade.php

Callum fixed the back end of this in CORE-186 (#1256) , however the actual value in the form was never changed accordingly

HOTFIX: V/T Facility Spaces

---

resources/views/site/atc/endorsements.blade.php

Updates AFISO Aerdromes as per **TRAIN-44**:
**Adds:** Barra (EGPR), Bodmin (EGLA), and Wolverhampton / Halfpenny Green (EGBO),
**Fixes:** Typo on "Old Sarum".
As requested by DC.

Updates AFISO Aerodromes

---

app/Listeners/Mship/SyncSubscriber.php
app/Models/Mship/Concerns/HasMoodleAccount.php
tests/Unit/Mship/Sync/AccountAlteredTest.php

Make comparators less specific. First statement should definitely catch null accounts...

Hotifx: Moodle Sync

---

app/Models/Mship/Concerns/HasStates.php
tests/Unit/Mship/MshipAccountTest.php
tests/Unit/Mship/MshipAuthenticationTest.php
tests/Unit/Mship/MshipRoleTest.php
tests/Unit/Mship/MshipStateTest.php

What was happening with these accounts was:
- The user (for some reason or another) had an old state that had not been ended, say USA USA-N
- They then transferred to say CAN USA-N. The existing logic kept on looking at this first original state each time, and so decided it needed to add the new state.
- `$this->primary_states` was returning their visiting state. As this isn't a permanent state, it didn't use the logic to remove it, thus creating a never ending loop of adding new states but not deleting the old ones.
Closes CORE-322

CORE-322 - Duplicate Account States

---

app/Http/Controllers/Slack/Registration.php

Will attempt to resend invitation if already exists.
Extends token life time to a week regardless.
Closes CORE-334

CORE-334 - Fix slack registrations expiring

---

app/Models/Training/WaitingListAccount.php
tests/Unit/Training/WaitingListAccountTest.php

Fixes a bug which didn't properly compute the status of an hour check for a member based upon their ATC NetworkData.

CORE-388 - Fix Hour Checking Bug

---

resources/views/site/atc/bookings.blade.php

Replaced 'Community Director' with 'Marketing Director' to keep the process up-to-date with the recent changes of delegated power among the staff team.

Updated The Process Of Event Approval

---

app/Libraries/TeamSpeak.php

With original code, nothing happened if their display name didn't contain their full name at all

Hotfix: TeamSpeak name validity logic

---

resources/views/site/staff.blade.php

https://community.vatsim.uk/news/atc-training/appointment-training-group-instructor-tgnc-r279/

new ATC staff changes

---

app/Console/Commands/NetworkData/ProcessNetworkData.php

Not supported with current production drivers (database)
Ref: https://github.com/Zizaco/entrust/issues/468

Remove flushcache method call

---

package.json

Builds have been failing on Heroku due to `cross-env` not being found.

Fix Heroku Cross-Env Reference

---

app/Models/Sys/Config.php
app/helpers.php
database/migrations/2019_10_13_164450_create_sys_config_table.php
database/migrations/2019_10_13_171328_add_notice_key.php
resources/assets/sass/app.scss
resources/views/components/nav.blade.php
tests/Unit/Sys/ConfigTest.php

This PR adds;
- Adds concept of "sys_config" where you can have a key, a value and decide whether it is active or not. This allows us to configure things on the fly without pushing new builds.
- Adds first implementation of this config by adding the ability to add a banner at the top of Core based on the value against the config key "notice".

Sys Config & Notice

---

package.json

- Defines explicitly the plugins we use (rather than just assuming the defaults are correct)
- Overrides the releasedLabel config value to `false` to prevent that label being added to PRs and issues after release.

Semantic Release Plugin Config

---

app/Models/Cts/Booking.php
tests/Feature/Account/Feedback/FeedbackUserSearchTest.php
tests/Unit/CTS/BookingsRepositoryTest.php
tests/Unit/Endorsements/ConditionModelTest.php

1) Tests\Unit\Endorsements\ConditionModelTest::itReturnsAListOfHumanPositions  assertArraySubset() is deprecated and will be removed in PHPUnit 9.
2) Tests\Unit\CTS\BookingsRepositoryTest::itCanReturnAListOfTodaysBookingsWithOwnerAndType  assertArraySubset() is deprecated and will be removed in PHPUnit 9.
3) Tests\Feature\FeedbackUserSearchTest::testItDoesNotReturnCurrentUser  Using assertNotContains() with string haystacks is deprecated and will not be supported in PHPUnit 9. Refactor your test to use assertStringNotContainsString() or assertStringNotContainsStringIgnoringCase() instead.
4) Tests\Feature\FeedbackUserSearchTest::testItReturnsAnotherUser  Using assertContains() with string haystacks is deprecated and will not be supported in PHPUnit 9. Refactor your test to use …

Remove Deprecated PHPUnit Functions

---

app/Console/Kernel.php

This is causing the queue to crash at the scheduled time each day

Hotfix: Stop syncing forum groups from scheduler

---

resources/lang/en/teamspeak.php

When Kicking an inactive member, the message is truncated due to Teamspeak message length limits. This is a shorter message.

Updates message when kicking an inactive member from Teamspeak

---

resources/views/mship/management/dashboard.blade.php

Small change to add the guide URLs in the panel footer. 
Let me know what you guys think, or if you want a separate guides page setting up with the content copied over I can do that.

Add guides in to dashboard

---

app/Http/Middleware/ApiTracking.php

Resolves #1554 
Exception being thrown because there is no apiRequest object. Amend Eloquent call to `firstOrFail()` to gracefully throw a 404 if it does not find the appropriate request in the database.

ApiTracking - firstOrFail

---

composer.lock

Bumps version of `cobaltgrid/vatsim-stand-status`, which implements a try catch around the VATSIM XML functions
Closes #1727

Fix: VATSIM Datafile Outage Effecting Airport Pages

---

resources/views/site/staff.blade.php

I removed the TG Managers section as they've been replaced by Member Services, and also I centered most of the role and team headings. Feel free to disagree with me on the centering, it may only bother me and not everyone else. See here:

Style: Remove TG Managers & center some texts

---

app/Events/NetworkData/AtcSessionEnded.php
app/Listeners/NetworkData/FlushEndorsementCache.php
app/Models/Atc/Endorsement.php
app/Providers/EventServiceProvider.php
tests/Unit/Endorsements/EndorsementModelTest.php

Busts a user's endorsement cache when a ATC session ends.
Currently, the overall status for an endorsement does not tally with the status for the individual conditions. This fix will cache-bust the user's endorsement-met status when their ATC session ends.

Feature - Endorsement cache bust on ATC session end

---

.github/workflows/build_and_test.yml
routes/web-public.php

- Merges with and without coverage tests so that we always run with coverage to simplify the process
- Swaps XDebug (installed by default) for PCOV to run coverage reports significantly quicker
- Runs tests on PHP 7.3 and PHP 7.4

Use PCOV For Coverage

---

.github/workflows/build_and_test.yml
routes/web-public.php

Ref: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags and https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags
We should ignore all pushes to tags as there is no point running the workflows twice on `master`

Ignore Tags on GitHub Actions

---

app/Console/Commands/ExternalServices/SyncTGForumGroups.php

Forum groups have been renamed so IDs remain the same.

Change RTS IDs For Forum Group Sync

---

config/horizon.php

We only really need to know if things are running super slowly - 10 minutes is fine.

Extend Horizon Notification Time

---

resources/views/site/community/vt-guide.blade.php

Removed reference to Scottish Control (SCO_CTR) on the VT-Guide.

Fixes #1822 Removed "Scottish Control (SCO_CTR)"

---

app/Jobs/UpdateMember.php

Resolves #1799 
Amended this to just catch all exceptions.
The facade this is using from the XML package is fairly simple and is only going to blow up if the request fails on CERT's side. Given that this will be replaced by the VATSIM API and Connect soon, I'm happy for this to just catch all exceptions and ignore them.
The other option is we check for multiple exception types;
`failed to open stream: HTTP request failed!` and `Name or service not known` are the two biggest offenders.

1799 - Handle CERT Down

---

app/Jobs/UpdateMember.php

Resolves #1756 
Example: https://cert.vatsim.net/vatsimnet/idstatus.php?cid=1430931
"None" was throwing an exception when trying to convert it to a DateTime... because... it isn't a date or time!

1756 - Handle GDPR Removed Reg Date

---

config/database.php

Increases to 90 seconds. Predis is abandoned and we should keep an eye out for alternatives that Laravel supports (PHPRedis potentially).

Redis read_write_timeout

---

app/Http/Controllers/Site/HomePageController.php

Migrates CTS next event request to HTTP facade, which won't throw an exception for 400 or 500 HTTP errors.
Fixes #1839

Fix: CTS Next Event 502 Exceptions

---

app/Models/Mship/Concerns/HasNovaPermissions.php

When a user had been previously added to a list, and then deleted, that user couldn't be deferred again because the `deleted_at` on the pivot was always going to be null as it wasn't defined in the relationship.
This PR fixes this by adding it into the pivot so it would only defer on the non-softDeleted WaitingListAccount.﻿

fix: deferral not being selected when previous been in list

---

app/Http/Controllers/UKCP/Token.php

Fixed #1858 
The `Storage` facade uses League's Flysystem so we need to catch that exception.

Properly Catch UKCP FileNotFound Exceptions

---

app/Http/Controllers/Api/OAuthUserController.php

Fixed #1865
Seems to be an issue for inactive users - they do not have an ATC rating in `mship_account_qualification` so we should not presume it'll be present, similar to how we handle pilot ratings a few lines below.

API Exceptions For ATC Rating

---

database/migrations/2020_08_10_164413_change_order_of_discord_columns.php

Names should be first, rather than three columns with id numbers / tokens relating to Discord.

Move Discord Id Columns

---

app/Models/Permission.php
config/permission.php
database/migrations/2019_07_20_085104_add_waiting_list_table.php
database/migrations/2020_01_31_180100_add_waiting_list_action_permissions.php
database/migrations/2020_02_01_095731_create_nova_feedback_permissions.php
database/migrations/2020_02_13_190400_create_add_student_admin_permission.php
database/migrations/2020_05_10_195144_create_telescope_permission.php
database/migrations/2020_05_11_184510_add_horizon_permission.php
database/migrations/2020_08_03_170100_add_discord_permissions.php

In the latest version of Laravel 7.25, there are issues with the Spatie permission package, because of changes made to how $guarded works (in light of a security issue).  This should resolve those issues until the package is updated.
cc: @CalumTowers <- he asked me to open this PR.

fix: permission name cannot be null, error

---

app/Notifications/Mship/DiscordInvite.php
resources/views/emails/mship/discord_invite.blade.php

Discord invite email, will be used to manually send to people that have joined us on Slack but not Discord, but may be useful in future too.

Discord Invite Email

---

app/Console/Kernel.php
app/Jobs/Middleware/RateLimited.php
app/Jobs/UpdateMember.php
app/Models/Permission.php

Does the following:
- Add rate middleware to the UpdateMember job to limit to 100 updates per 60 seconds
- Reinstates the hourly Cert Update Job
- Increases Monthly update frequency to tri-monthly
- Increase the capacity of the all-members job
Closes #1896

fix: CERT Update update frequency

---

config/horizon.php

Balance them between queues and then allow them to scale up - we have the overhead in production to account for this.

Auto Scale Queue Workers

---

app/Http/Controllers/Site/HomePageController.php

If someone left the division, we were still counting them in the stats on the homepage.

Homepage Stat Error

---

app/Models/Mship/Account.php
database/migrations/2020_08_10_164240_remove_slack_id_column.php
phpunit.xml
resources/views/components/top-notification.blade.php
resources/views/mship/management/dashboard.blade.php
tests/Unit/Account/AccountModelTest.php

- Removes remaining Slack references in code and from the user's point of view
- Drops the `slack_id` column
Resolves #1879

1879 - Remove Slack References

---

config/horizon.php

Increases to 6 hours, to prevent notifications firing off when there are long running processes overnight.

Increase Queue Alerts For user_sync

---

app/Console/Commands/Members/UpdateMembers.php
app/Console/Kernel.php

The automated updates from CERT (using `Members:CertUpdate`) are currently flawed in a number of ways.
- It primarily focuses on users that have logged in, despite users being updated when they login automatically, thus not needing to be synced by this command
- It limits the number of members being captured that have never logged in by capping it at 1000 people every 30 days. This results in us holding outdated data on members as we never get a chance to clear the backlog
- It has very little chance to update inactive members - again, resulting in outdated data (e.g. for right to be forgotten requests)
My proposal, and contained within this PR, is that we process updates once per hour, the same way each time. Each run is capped at 1000 members and queued on a dedicated queue as it is …

1944 - CERT Sync Schedule Change

---

app/Jobs/UpdateMember.php

Example: https://cert.vatsim.net/cert/vatsimnet/idstatus.php?cid=1476109
When this is eventually refactored to call the new API (#1736), we will handle returns of a 404 a little better. Its quite difficult to do here as it is buried in the `VatsimXML` package.
I believe the easiest approach for now, as I've implemented here, is to stamp the member's `cert_checked_at` regardless of whether the check itself was successful or not. An attempt was made, so they need to go to the back of the queue for the next batch of checks.

Stamp Cert Checked For Failure

---

app/Models/Mship/Account.php

The `SyncSubscriber` (which triggers syncs of users to CTS, Helpdesk, Moodle & Discord) only runs when `$event->account->fully_defined` is true.
Sometimes, users appear in the feed without a rating, and this causes issue when we try to sync them to external services. All users should have at least an "OBS" rating, thus `$this->qualification_atc` would not be null and return true for this method.
Resolves #1981

1981 - Include ATC Qualification In "Fully Defined"

---

app/Models/TeamSpeak/Registration.php

This PR will be easier to review with the stack trace in #1984 
The TeamSpeak library is throwing an exception incorrectly.
When removing a registration, we first check that there is a privilege key in our system (stored in `teamspeak_confirmation`) associated with the registration being deleted.
We then delete it from TeamSpeak (`$tscon->privilegeKeyDelete($this->confirmation->privilege_key);`) and then remove it from our database (`$this->confirmation->delete();`).
The first line is throwing a `TeamSpeak3_Adapter_ServerQuery_Exception` exception even though the exception message is `ok` and the privilege key is removed on TeamSpeak. The result it that the privilege key isn't removed from our system and the registration also is not removed - throwing an error to the user.
This is not the …

1984 - TeamSpeak Registration Deletion Fix

---

app/Http/Controllers/Auth/LoginController.php

If a user logs in and does not provide us with any of the personal permissions we risk running `->name_first`, `->name_last` or `->email` on `[ ]`, resulting in an error.
Fixed #1980

1980 - Fix Login Validation

---

.github/workflows/deploy.yml

- Only run deployment script after the trigger has ran (which comes from release, which comes after testing)
- Tidy up file by removing `.env` generation in favour of storing the entire thing in secrets

Deployment Script Amends

---

resources/assets/sass/home.scss
resources/views/site/home.blade.php

- Issue on Safari where header would scroll with the page, blocking content
- Issue on Chrome where the next even was pushed off of the page

Fix Homepage Layout Issues

---

app/Console/Commands/NetworkData/ProcessNetworkData.php
app/Console/Kernel.php

- Disables Discord Manager whilst we try and improve performance
- Extends grace period for network data
- Adds error handling for when the network data feed is unavailable
- Improves output of the `networkdata:download` command to show progress
- Small refactors within the network data command

Console / Network Data Improvements

---

resources/views/site/atc/endorsements.blade.php

Removed erroneous apostrophes (generally after acronyms which need to be pluralised, not made possessive)
Updated Swanwick Mil references after re-sectorisation
Updated Gatwick stats based on the [Ops New Year Review](https://community.vatsim.uk/news/operations/operations-new-year-review-topsky-and-2020-statistics-r367/)

Updates to Endorsements page

---

app/Models/Mship/Concerns/HasQualifications.php
tests/Unit/Account/AccountModelTest.php

Selects the primary qualification based on the "vatsim" code, rather than date added

Fix - Primary Qualification Selection

---

app/Http/Controllers/Auth/LoginController.php

Utilise required_scopes on OAuth requests to reduce chance of user unselecting and then getting an error message.
Disables the ability to deselect the requested scopes.

Feat - Utilise .NET Auth required_scopes

---

app/Console/Commands/ExternalServices/ManageDiscord.php
tests/Unit/Command/DiscordManagerTest.php

Stops the execution of the `processSuspendedRole` function if they already contain the role.

Stop duplicate suspended role operation

---

resources/views/site/operations/sectors.blade.php

EGNO_R_APP isn't mentioned in the change note. I've assumed that the military use of _R_APP will follow the same convention.....

Remove _R from approach

---

resources/views/site/operations/sectors.blade.php

[MAN_CTR changed](https://community.vatsim.uk/topic/37462-2020-12-03-pc-bandbox-man_ctr-frequency-change/) from 118.775 to 133.200
[SCO_WD_CTR changed](https://community.vatsim.uk/topic/37425-2020-12-03-scottish-ac-west-deancross-bandbox-frequency-change/) from 133.200 to 133.875

Updated MAN and SCO_WD frequencies

---

nova-components/WaitingListsManager/src/Http/WaitingListsManagerController.php

I can't fully test this on the right dataset but this is the best way I can think of to reduce the N + 1 issues with the waiting lists.
It eager-loads the attributes used in queries; no breaking changes as all unit and feature tests pass. Will be interested to see how it performs in production.

Address query issues with waiting lists

---

.github/workflows/deploy.yml

The change to the permissions on $SHARED_DIRECTORY was failing due to the `github` service user not owning the files within said directory. However, this is handled in other ways for a task which just removes anonymous access.

Remove change to permissions on $SHARED_DIRECTORY

---

.github/workflows/deploy.yml

`teamspeak-daemon` is no longer used as command moved to Core's scheduler.

Remove references to `teamspeak-daemon` service in Actions Deployment

---

.github/workflows/deploy.yml

As Actions is event-driven, multiple successive PR merges currently resulting in multiple concurrent deployments. This change adds https://github.com/softprops/turnstyle to the workflow to enforce them to queue for any existing deployment jobs to complete. 
The timeout is also added which will support waiting for ~3 builds to complete + the time for the workflow itself.

Add support for serialised deployment workflows

---

app/Jobs/Mship/SyncToDiscord.php
app/Models/Mship/Concerns/HasDiscordAccount.php

At present, jobs are backing up in the queue because we are rate limiting very generously to avoid hitting issues with Discord API limits.
Instead, we'll just reintroduce the delays between Discord API calls and allow the jobs to run for slightly longer periods of time on the queue.
This shouldn't cause us great numbers of issues now that we are syncing Discord users whenever the user changes, rather than all ~2000 users at once.

Extend Time of Discord Sync

---

.github/workflows/deploy.yml
app/Console/Kernel.php
resources/views/errors/503.blade.php

Rather than syncing the scheduled jobs (with Oh Dear) on a daily basis, we should just handle this as part of the deploy script - as that is the only time they will ever change.
Also in this PR;
- Rewording the 503 page to make it clear it is downtime
- Reworking the order of deployment steps whilst `artisan down` is in effect to minimise downtime

Sync Scheduler on Deploy

---

app/Events/Mship/Roles/RoleAssigned.php
app/Events/Mship/Roles/RoleRemoved.php
app/Listeners/Mship/SyncSubscriber.php
app/Models/Mship/Account.php
app/Models/Mship/Concerns/HasDiscordAccount.php
app/Models/Mship/Concerns/HasRoles.php
database/factories/ModelFactory.php
tests/Unit/Account/Relationships/RoleTest.php
tests/Unit/Account/Sync/AccountAlteredEventTest.php
tests/Unit/Account/Sync/RoleSyncTest.php

This PR;
- Introduces two new events that fire when a role is assigned or removed from a user
- Adds the two new events to the SyncSubscriber so that when a role is added or removed, it syncs the user to external services
- Adds some missing tests for Discord to assert that the job was added to the queue

Auto Sync Role Changes

---

app/Models/Mship/Concerns/HasDiscordAccount.php

`$this->` was left over from when this was a command and not a trait.

Fix Suspended Role Id

---

app/Console/Commands/TeamSpeak/TeamSpeakManager.php

Basic check to abort if `$tscon` is `null`

Check for tscon Before Processing TeamSpeak Users

---

app/Models/Mship/Account.php
app/Models/Mship/Concerns/HasDiscordAccount.php
resources/views/teamspeak/new.blade.php

Discord limits nicknames to a maximum of 32 characters. In the event that a full name (e.g. `name_first` and `name_last`) is greater than 32 characters, the API will throw an exception when attempting to set the nickname.
This PR;
- Introduces a method to get the user's first name; either the set `nickname` or `name_first`. This is accessed via `$account->firstName`.
- Refactors the `$account->name` to defer to the new `$account->firstName` to get either the `nickname` or `name_first`.
- Adds a method to the `HasDiscordAccount` trait to get the user's "Discord name". This will be their full name (either nickname or first name, space, then surname) or, in the event that this would be over 32 characters, it will replace their surname with their initial.
The hole in this PR will be that if …

Handle Discord Name Limit

---

app/Listeners/VisitTransfer/SyncVisitingControllerToCts.php
app/Models/Mship/Concerns/HasCTSAccount.php
app/Providers/EventServiceProvider.php
resources/views/site/operations/sectors.blade.php

Not the finest bit of code, but it does appear to work. I don't have a full live CTS to test against locally, but this matches what data is expected in the production system for a visiting controller.
The logic for the internal IDs is straight from CTS. I dare not simplify it in case it is somehow messed up (there is a refactoring opportunity I can spot straight away with the boolean logic.). 
Also, there are often things not worth unit testing. I firmly put this in that category.

feat: Sync visiting controllrs to CTS when accepted

---

app/Http/Controllers/Atc/EndorsementController.php
resources/views/components/nav.blade.php
resources/views/controllers/endorsements/area.blade.php
routes/web-main.php
tests/Feature/Atc/AreaHourCheckTest.php

Uses existing endorsement mechanism for checking conditions in line with the same checks the waiting lists uses.
The only 'caveat' is that it will never work with checks which have '_APP' as the callsign.

feat: Add Area hour checker

---

app/Models/Atc/Endorsement/Condition.php
app/Models/Mship/Concerns/HasCTSAccount.php
database/factories/EndorsementFactory.php
database/migrations/2021_08_05_165824_add_required_qualification_column_to_endorsement_criteria.php
tests/Unit/Endorsements/ConditionModelTest.php

This adds a column to the endorsement condition table to mandate that the sessions take place when the user has a specific rating. e.g. 10 hours in 6 months when the session has an S3.
For this to take effect in production, you will need to clear the cache and load the waiting lists page.

feat: add required qualification to condition

---

app/Console/Commands/CtsMock.php
app/Models/Mship/Concerns/HasCTSAccount.php

fix: Use null instead of empty date for joined_div in cts sync

---

.github/workflows/test.yml
app/Console/Commands/Members/ImportMembers.php
app/Console/Kernel.php
app/Listeners/Mship/SyncSubscriber.php
app/Models/Mship/Account.php
app/Models/Mship/Concerns/HasQualifications.php

The current `ImportMember` script was disabled in production. Upon enabling it, I found a few issues and rather than digging into each one decided to try and clean it up a tad.
Given that we now have the `AccountAltered` event, the only thing this command needs to do is create the initial account with the minimum information required. Everything else (qualifications, states etc) will be handled by the subsequent run of the `SyncSubscriber`.
To use this command, you will need;
- A VATSIM API key for GBR
- To ensure that your database is running with the timezone of +00:00 (SELECT @@global.time_zone; / SET GLOBAL time_zone = '+00:00';) as some users have a registration date that is in a time that doesn't exist in BST (e.g. 01:05AM on the day clocks change)
The command will;
- Fetch all …

Import Member Re-Write

---

app/Console/Commands/Members/ImportMembers.php
app/Console/Kernel.php
app/Models/Mship/Account.php

Currently, the ImportMembers command gets all members from the API and loads them into memory. Tens of thousands of collections loaded does have an impact on memory usage.
My first thought was to discard each member from the collection as they are processed, but the first 2-3 minutes of the command being ran was still quite resource intensive.
I've now refactored the command so that instead of loading all of the members into memory, we process one page of the API at a time on the fly before returning back to the API for the next batch, processing them and repeating. I have also updated the console output to help show the progress across these calls as below.
Also included within this PR is an update that now processes the member's ATC rating, Pilot rating, Division & Region. This means …

Import Members Performance Improvements

---

database/migrations/2021_11_07_195238_modify_network_callsigns.php

Recently network callsign length restrictions were raised to 12 chars (from 10). This PR ups our internal DB fields to a max length of 20 - hopefully futureproofing against any other future changes to this.
Should fix the issues we have been seeing re:network data download failing - (see https://sentry.io/organizations/vatsim-uk/issues/2538159389/?project=5734564&query=is%3Aunresolved)

fix: Network callsign length

---

app/Http/Controllers/Auth/LocalBanDisplayController.php
app/Http/Middleware/DenyIfBanned.php
resources/views/errors/banned-local.blade.php
resources/views/errors/banned-network.blade.php
routes/web-main.php
tests/Feature/Middleware/BannedMiddlewareTest.php

Adds context to the banned screen for members who have a network or local VATSIM UK ban.
This is designed to help members contact the right people more readily should they need, and ultimately leave them more informed about their membership status.
Preview Local Ban:

feat: Add more informative 403 messages

---

resources/views/site/atc/newcontroller.blade.php
resources/views/site/staff.blade.php

Just noticed this on the website; the role titles for the ATC/Pilot Training Manager changed away from 'General Manager' ~two years ago (see for example Discord roles).

Training teams: General Manager to ATC/Pilot Training Manager

---

resources/views/site/operations/sectors.blade.php

Sorry for another one!
1. I made a mistake with the TC NE responsibilities, so have removed Luton.
3. The term 'airways' is no longer used; replaced with 'joining clearance' instead.

style: Fixed sectors page errors

---

resources/views/ukcp/token/guide.blade.php

Was still pointing at the old ones, hence why people are having setup issues!

fix: ukcp c++ redists url

---

config/vatsim-api.php

we've lost access to the vatsim.dev domain name, so an update to the URL is required

update vatsim api url

---

resources/views/mship/management/dashboard.blade.php

Recent questions were raised via Discord about the invisibility function on the core dashboard. This seeks to clarify its purpose.

style: clarify invisibility management on mship dashboard

---

database/migrations/2022_12_13_131128_index_networkdata_for_account_disconnected_and_callsign.php

This is an experiment to address long-standing performance issues with querying lots of network data at any time.
The three indexes added cover:
- Endorsement condition querying
- Waiting list base 12-hour check (think isUK() scope on the networkdata_atc model)
- Querying for UK network data in any other (before or after the disconnected_at check) usecase
There is a potential this will increase disk usage.
The main motivation for these changes is to potentially remove the need for caching on the waiting list eligibility checking
and thus reducing the overall complexity of this bit of the application.
Relevant Sentry Tracing:
- https://sentry.io/organizations/vatsim-uk/performance/summary/spans/db.sql.query:a24f8f1356d21c38/?project=5734564&query=http.method%3AGET&statsPeriod=24h&transactio …

perf: add database level indexes for networkdata_atc table

---

app/Models/Cts/TheoryResult.php
app/Models/Training/WaitingList/WaitingListAccount.php
database/factories/Cts/TheoryResultFactory.php
database/factories/WaitingListFactory.php
database/migrations/2022_12_14_103127_add_cts_exam_column.php
nova-components/WaitingListsManager/resources/js/components/BooleanIndicator.vue
nova-components/WaitingListsManager/resources/js/components/Bucket.vue
nova-components/WaitingListsManager/resources/js/components/FlagIndicator.vue
nova-components/WaitingListsManager/resources/js/components/Tool.vue
nova-components/WaitingListsManager/src/Http/WaitingListAccountResource.php
tests/Database/MockCtsDatabase.php
tests/Unit/Training/WaitingList/WaitingListAccountCtsTheoryTest.php

Adds a field to the waiting list index page for ATC lists which indicates whether or not a theory exam
pass has been detected for the user in the list.
The waiting list detects which theory exam to look at via a nullable column in the `training_waiting_list`
table. This will need to be filled out on rollout for each respective level of a waiting list.
This relates to the `exam` field on the `theory_results` table.
The theory_results table in CTS is indexed first on student_id so that additional filtering will be done on
a small number of rows in the logic added to `WaitingListAccount`.
Other changes:
- Added a model for theory exam results which maps to the `theory_results` table in CTS.
- Refactored `Bucket.vue` to have a generic true/false indicator without having to rely on the object …

feat: add theory exam pass status to waiting list index

---

app/Listeners/Training/WaitingList/CheckWaitingListAccountMshipState.php
app/Nova/Actions/Training/AddStudentToWaitingList.php
database/migrations/2023_03_24_165127_waiting_lists_home_members_only_flag.php
tests/Unit/Training/WaitingList/WaitingListAccountStateChangeTest.php

This PR:
- Creates a flag which can be set per waiting list, which determines if accounts must be a home member to join the list
- Updates the AccountAltered event listener to respect the above flag
- Updates the Waiting List Manager controller to respect the new flag when adding an account
- Updates / creates tests relevant for this task

Feat: Waiting list home members only flag

---

app/Models/Mship/Feedback/Feedback.php
resources/views/mship/feedback/view.blade.php

Hi,
I have made a few changes to the publicly accessible feedback page. This is my first 'play around' with core so I'm still learning, any feedback/comments with improvements for next time are much appreciated.
<hr />
I propose we remove the "Message From" which displays the staff member who sent the feedback (which seems to confuse some members) with a more useful "Callsign" to display the position the user was on when the feedback was received. 
All the best!

Add callsign to viewable feedback

---

resources/views/visit-transfer/site/application/terms.blade.php
resources/views/visit-transfer/site/application/view.blade.php

Hi, 
We recently removed the date from the VT acceptance email that said "you must engage with training within 90 days (*this date)"
It's been pointed out that it was still on the website and was worrying some people. The 90 days starts from when we offer them training so this date from the dashboard should be removed.
Thanks,

refactor:Remove Date from VT Dashboard

---

app/Http/Controllers/Site/PilotPagesController.php
resources/views/site/home.blade.php
resources/views/site/pilots/stands.blade.php
routes/web-public.php
tests/Feature/Site/PilotPagesTest.php

Adds a guide for pilots regarding how stands are assigned in VATUK and the features of UKCP available to them.

feat: stand guide

---

app/Http/Controllers/UKCP/Token.php
app/Libraries/UKCP.php
resources/views/mship/management/dashboard.blade.php
routes/web-main.php
tests/Unit/UKCPLibraryTest.php

Revamps the dashboard for UKCP to make it consistent with the new setup method. Removes manually creating and downloading keys via Core.

Ukcp dashboard revamp

---

app/Jobs/UpdateMember.php
app/Models/Mship/Concerns/HasQualifications.php
app/Models/Mship/Qualification.php
tests/Unit/Mship/QualificationDetectionTest.php

This fixes the reported trello bug where P0 members were being granted pilot ratings upto P5. This was due to the bitmask logic when parsing the ratings squaring a negative number (-1) and then shifting all the way upto P5.
This also supports pilot ratings for Flight Instructor & Flight Examiner via UpdateMember and allows the new behaviour when these ratings are revoked in favour of previous permeanant pilot ratings.

fix: handle -1 pilotrating bitmask and pilot rating revokation

---

resources/views/site/atc/endorsements.blade.php

Updates to the AFIS/AG endorsement list for 2311.
To be released/updated on 1st November please.

AFIS/AG Endorsement list AIRAC 2311

---

app/Http/Controllers/Mship/Feedback.php
routes/web-main.php
tests/Feature/Account/Feedback/FeedbackTest.php

A little poc for prefilling the usercid in e.g the atc feedback form.
Saw some discussion on discord about trying to search for a controller name in order to submit feedback, I know I've been asked by pilots what my CID is so they can submit feedback about me (good feedback I hope!)
This fills the `Question` with slug `usercid` if the `usercid` is present in the query params.
Because the link to the new atc feedback form is quite long and getting a query param through a url shortener (`vats.im/atcfb`) is challenging I've also added a short url to the atc feedback form (`vatsim.uk/atcfb`)
My intention would be to use it in euroscope profiles as `Submit feedback at vatsim.uk/atcfb?usercid=12345678`).
Keen to know your thoughts, further notes below.
-------------
I believe the url shortener …

feat: Prefill usercid in feedback forms

---

app/Http/Controllers/Atc/EndorsementController.php
app/Http/Controllers/BaseController.php
resources/views/controllers/endorsements/gatwick_ground.blade.php
tests/Feature/Atc/GatwickEndorsementTest.php

Re-Implement Gatwick Endorsement requirements page for the new requirements, and update some language as necessary.
Endorsement page checks for
- 50 hours as DEL or GND in the UK based on Network Atc role data
- Home division membership
- Active on Roster
- Holding an S1
All working based on tests / qa, would appreciate a review of the language in the requirement descriptions.

TECH-245 Gatwick Endorsement Requirements Page

---

app/Events/Mship/Endorsement/TierEndorsementAdded.php
app/Listeners/Mship/Endorsement/NotifyOfTierEndorsement.php
app/Models/Mship/Account/Endorsement.php
app/Notifications/Mship/Endorsement/TierEndorsementNotification.php
app/Observers/EndorsementObserver.php
app/Providers/EventServiceProvider.php
resources/views/emails/mship/endorsement/tier_endorsement_granted.blade.php
tests/Feature/Admin/EndorsementRequest/EndorsementRequestApprovalTest.php

This establishes a pattern for sending events from Endorsement events and adds a notification
to inform a user they have been endorsed on a PositionGroup aka. Tier 1 / 2 endorsement.

feat: notify users upon being granted a permanent endorsement aka. PositionGroup

---

app/Http/Controllers/Atc/EndorsementController.php
resources/views/components/nav.blade.php
resources/views/controllers/endorsements/gatwick_ground.blade.php
resources/views/controllers/endorsements/heathrow_ground_s1.blade.php
resources/views/site/atc/endorsements.blade.php
routes/web-main.php
tests/Feature/Atc/HeathrowS1EndorsementTest.php

Add a page detailing requirements for the heathrow s1 endorsement, easy to do using the same approach as the gatwick page.
No ticket in linear for this afaik.

feat: Heathrow s1 page

---

app/Http/Controllers/Atc/EndorsementController.php
database/migrations/2018_02_10_180736_add_kkgnd_endorsement.php
tests/Feature/Atc/HeathrowS1EndorsementTest.php

Corrects migration from 2018 to use new name, this will help local work and tests, will not run in prod.
Hopefully the name is now correct, could someone with access to prod data please check?

fix: Use correct gatwick endorsement name (has changed in the past).

---

resources/views/site/pilots/stands.blade.php

Update stand request URL on `/pilots/stand-guide` as the old UKCP url (https://ukcp.vatsim.uk/admin/request-a-stand) returns a 404 now.

Update stand request url

---

resources/views/site/pilots/stands.blade.php

Removes `/admin` from the UKCP url.
Same issue as in https://github.com/VATSIM-UK/core/pull/3655 I've just missed this second url

remove /admin from UKCP link

---

app/Models/Discord/DiscordRoleRule.php
database/migrations/2024_06_26_185221_add_endorseable_to_discord_role_rules.php
tests/Unit/Discord/DiscordRoleRuleTest.php

Allows Discord role rules to be linked to either Positions or PositionGroups.
Whilst we don't do any that are directly related to positions right now, it may be useful in future.
Fixes TECH-236.
Go live script
```
INSERT INTO `discord_role_rules` (`name`, `discord_id`, `permission_id`, `qualification_id`, `state_id`, `cts_may_control_contains`, `endorsable_type`, `endorsable_id`) VALUES
('LL APP Endorsement', 1115367609450381363, NULL, NULL, NULL, NULL, 'App\\Models\\PositionGroup', 11),
('LL GND Endorsement', 1115367317510037596, NULL, NULL, NULL, NULL, 'App\\Models\\PositionGroup', 18),
('LL TWR Endorsement', 1115367506232746086, NULL, NULL, NULL, NULL, 'App\\Models\\PositionGroup', 10),
('Shanwick Controller', 989268023091277885, NULL, NULL, NULL, NULL, 'App\\Models\\PositionGroup', …
```

Support Endorsement Role Sync within Discord Manager

---

app/Http/Controllers/Api/CTS/ValidationsController.php
app/Http/Controllers/Api/ValidationsController.php
routes/api.php
tests/Feature/API/ValidationTest.php

Update the API endpoint that originally used CTS validations to instead look at the roster.
Not the most efficient iterating through everyone on the roster but it is pretty quick with production data.
Resolves TECH-274.

Update Validations API for Roster

---

readme.md
resources/views/mship/waiting-lists/_waiting_lists_list.blade.php

Due to a lil snafu this has been broken for a while, should restore properly showing if you have passed the CTS exam for atc & pilot lists

Fix: Waiting lists list not listing theory exame corrects

---

app/Models/Mship/Concerns/HasWaitingLists.php

Whoops!
Users with places on soft deleted waiting lists could not have their waiting lists retrieved due to an accidental null object access. This broke login as waiting list eligibility is recalculated at login.

fix: Soft deleted waiting lists would crash waiting list retrieval

---

app/Models/Mship/Concerns/HasWaitingLists.php
tests/Unit/Account/Relationships/AccountWaitingListsTest.php

Add some tests for retrieving waiting lists when some of the lists are soft deleted (these won't appear). Fix the same behaviour for current and soft deleted waiting list positions.
See #3880

fix: Tests for soft deleted waiting lists

---

app/Filament/Resources/WaitingListResource/Widgets/IndividualWaitingListOverview.php
tests/Feature/Account/WaitingListsTest.php

Overview widget was still using WaitingListAccount as pivot, missed in big refactor

Waiting list overview widget fix

---

app/Filament/Resources/SoloEndorsementResource.php
app/Filament/Resources/SoloEndorsementResource/Pages/ListSoloEndorsements.php
database/seeders/RolesAndPermissionsSeeder.php
tests/Feature/Admin/SoloEndorsement/Pages/ListSoloEndorsementPageTest.php

This adds an overview page to allow ATC staff to see active and expired Solo endorsements, their duration and when active endorsements expire.

feat: add Solo Endorsement overview on admin panel

---

.devcontainer/docker-compose.dev.yml
.devcontainer/load-dotenv.sh

This PR adds a development-only compose config, taken from https://github.com/VATSIM-UK/core/blob/main/.devcontainer/docker-compose.yml but excluding core itself.
Also a utility script in `.devcontainer/load-dotenv.sh` has been added which will load all env variables defined in .env and pass them onto the command executed.
For example:
```sh
.devcontainer/load-dotenv.sh docker-compose -f .devcontainer/docker-compose.dev.yml up
```

Add development-only docker compose

---

resources/views/site/operations/landing.blade.php

Make references to new docs.vatsim.uk instead of forum.
Note: I can't test this, but hopefully I've not done anything stupid.

Update OPS docs links

---

app/Services/Training/WaitingListSelfEnrolment.php
database/migrations/2025_04_21_130040_add_self_enrolment_hour_requirements.php
tests/Unit/Training/WaitingList/WaitingListSelfEnrolmentServiceTest.php

Flirted with the idea of having an index over `account_id,qualification_id` but I don't think the volume of data is sufficient.
Equally flirted with having the 'hours' column as a 'minutes' column to avoid some floating point stuff but didn't think it added much really.
If anyon has a better idea for those column names I'm all ears...

Add ability to toggle self-enrolment for a minimum number of networkdata atc hours at given qualification

---

app/Notifications/Roster/RemovedFromRoster.php
app/Notifications/Training/RemovedFromWaitingListInactiveAccount.php
app/Notifications/Training/RemovedFromWaitingListNonHomeMember.php
resources/views/emails/mship/s1_training_opportunities.blade.php
resources/views/emails/training/waiting_list_inactive_account.blade.php
resources/views/emails/training/waiting_list_non_home_removal.blade.php
resources/views/errors/banned-local.blade.php
resources/views/livewire/roster/index.blade.php
resources/views/site/atc/landing.blade.php
resources/views/visit-transfer/emails/applicant/status_changed.blade.php

Replaces any references to Member Services across core with the rebranded Community
It was pointed out to me that it was incorrect on the roster so I thought id update them all, something I didn't want to burden you guys with...

Style: Replace references to Member Services with Community

---

app/Http/Controllers/Api/CtsController.php
app/Repositories/Cts/BookingRepository.php
routes/api.php
tests/Unit/CTS/BookingsRepositoryTest.php

This PR introduces a GET `/api/cts/bookings?date=YYY-MM-DD` route which returns  a list of CTS bookings on that date.
Minimum allowed date is `now - 30 days`

feat: add CTS booking API

---

app/Filament/Resources/WaitingListResource/RelationManagers/AccountsRelationManager.php
app/Filament/Resources/WaitingListResource/Widgets/IndividualWaitingListOverview.php
app/Listeners/Training/WaitingList/CheckWaitingListAccountInactivity.php
app/Listeners/Training/WaitingList/CheckWaitingListAccountMshipState.php
app/Models/Training/WaitingList.php
app/Models/Training/WaitingList/Removal.php
app/Models/Training/WaitingList/RemovalReason.php
app/Models/Training/WaitingList/WaitingListAccount.php
database/migrations/2025_05_11_030824_add_removal_reason_and_deleted_by_to_waiting_list_account.php
database/migrations/2025_05_12_193249_add_removal_comment_to_training_waiting_list.php
tests/Feature/Admin/WaitingLists/Pages/ViewWaitingListPageTest.php
tests/Feature/Training/WaitingListInactivityIntegrationTest.php
tests/Unit/Account/Relationships/AccountWaitingListsTest.php
tests/Unit/Training/WaitingList/WaitingListAccountStateChangeTest.php
tests/Unit/Training/WaitingList/WaitingListTest.php

feat: Waiting list removal reason tracking

---

app/Filament/Resources/WaitingListResource/RelationManagers/AccountsRelationManager.php

Fixes TECH-370
No more 'all' option on waiting lists!
< Please provide screenshots if this will facilitate a faster review of these changes>

text-370 fix: allow 25, 50, or 100 per page in waiting lists, no more all crashing everything on big lists!

---

app/Filament/Resources/WaitingListResource.php
app/Filament/Resources/WaitingListResource/Pages/EditWaitingList.php
app/Filament/Resources/WaitingListResource/Pages/ViewWaitingList.php
app/Policies/Training/WaitingListPolicy.php
database/seeders/RolesAndPermissionsSeeder.php
tests/Feature/Admin/WaitingLists/Pages/ViewWaitingListPageTest.php

Builds on work done in #4097.
Adds:
- Permission for waiting list admin defined by department (will be added to existing waiting list admin roles)
- Defines the Edit page for the WaitingList resource to allow it to be modified.

Allow waiting list admins to self-serve waiting list advanced settings

---

resources/views/auth/login.blade.php

Fixes #4167 
Changed the IDs from ```confirm``` to ```confirmPasswordReset``` and ```confirmLogout``` respectively to avoid them being duplicates.

Fixes #4167 - Remove duplicate button ```id``` attributes on login page

---

resources/views/auth/login.blade.php
resources/views/emails/default.blade.php
resources/views/emails/mship/member_email.blade.php
resources/views/errors/401.blade.php
resources/views/errors/403.blade.php

Fixes #4168
Changed web support email on the login page from ```web-support@vatsim.uk``` to ```technology-support@vatsim.uk```
There are 4 other places on the website which still use ```web-support@vatsim.uk```, should I change these in this pull request as well?

Fixes #4168 - Correct ```web-support email``` on login page to ```technology-support```

---

app/Filament/Resources/AccountResource/Pages/ViewAccount.php
app/Filament/Resources/AccountResource/RelationManagers/NotesRelationManager.php
app/Livewire/Roster/Show.php
app/Models/Roster.php
database/migrations/2025_06_24_181237_add_roster_note_type.php
database/migrations/2025_06_24_181633_add_roster_restriction_note_column.php
database/seeders/RolesAndPermissionsSeeder.php
resources/views/livewire/roster/show.blade.php
tests/Feature/Admin/Account/Pages/ViewAccountPageTest.php
tests/Feature/Roster/ShowTest.php

- Adds new column to roster table to link current restriction note
- Adds new note type 'roster'
- Adds facility to add, edit and remove roster restrictions on account which is on the roster
- Shows the active note on the roster page without the facility to search by position as usual.

Add ability to add free text roster restriction for account

---

app/Filament/Resources/WaitingListResource.php
app/Filament/Resources/WaitingListResource/RelationManagers/AccountsRelationManager.php
app/Filament/Resources/WaitingListResource/Widgets/IndividualWaitingListOverview.php
app/Models/Training/WaitingList.php
app/Policies/Training/WaitingListPolicy.php
app/Services/Training/WaitingListSelfEnrolment.php
database/migrations/2025_06_29_194053_add_max_capacity_to_training_waiting_list_table.php
tests/Feature/Account/WaitingListCapacityFeatureTest.php
tests/Feature/Admin/WaitingLists/WaitingListCapacityAdminTest.php
tests/Unit/Training/WaitingList/WaitingListCapacityTest.php
tests/Unit/Training/WaitingList/WaitingListSelfEnrolmentCapacityTest.php

Introduces a max_capacity field to training waiting lists, including migration, model logic, admin UI, and enforcement in self-enrolment and manual addition. Adds comprehensive feature and unit tests to verify capacity enforcement, admin management, and self-enrolment behavior.
Fixes TECH-379.

Add capacity limits to training waiting lists

---

app/Filament/Resources/AccountResource.php
resources/views/site/atc/endorsements.blade.php

Fixes #4186
Made ```Primary Email``` a ```CopyablePlaceholder```, this will mean it is no longer a ```form field```, this means it is read only. Let me know if the ```Primary Email``` has to remain as a text input specifically. I've made the formatting match the copying option from the ```CID``` field at the top of the same page for consistency.

Fixes #4186 - Add ability to copy email from account in admin panel

---

app/Filament/Resources/AccountResource/RelationManagers/EndorsementsRelationManager.php

Fixes TECH-392
Permanent/unexpired endorsements now have hidden duration. Duration is only shown for endorsements with set expiry.

TECH-392 Hide duration for permanent endorsements

---

app/Console/Commands/TeamSpeak/TeamSpeakDaemon.php

Fixes TEXT-399
Letters and numbers are scary and we don't want to scare people

fix: Return management bot name to something friendly

---

app/Filament/Admin/Resources/AccountResource/Pages/ListAccounts.php
app/Filament/Admin/Resources/AccountResource/RelationManagers/FeedbackRelationManager.php

Fixes #4198 
Change default sorting order to descending by the date the feedback was created.

Fixes #4198 - Sort member feedback in accounts view by most recent first

---

resources/views/visit-transfer/site/application/terms.blade.php

Fixes *nil*
Add a missing csrf token to the form
Application now properly redirects to `visit-transfer/application/<id>/facility`

Add missing csrf to vt-application start

---

resources/views/site/community/teamspeak.blade.php

Update the TeamSpeak registration page to state that TeamSpeak 3 is required for registration as TeamSpeak 6 does not have the ability to register via one time privilege key.
Before:
After:

Update to state TeamSpeak 3 client required

---

app/Console/Commands/Training/WaitingListRetentionChecks.php
app/Jobs/Training/WaitingListRetentionEmail.php
app/Jobs/Training/WaitingListRetentionRemoval.php

Fixes *#nil*
Now we ignore retention checks older that 6mo + those which do not have a waiting list account

Start ignoring old CTS retention checks

---

.development/hooks/README.md
.development/hooks/pre-commit
composer.json
hooks/README.md
readme.md

As it says on the tin. Rolling something simple for now to save our poor pipeline when I forgot to run lint.

Add pre-commit hook to run composer lint

---

resources/views/components/nav.blade.php

Removed the two <*li> from the page, so that the policies are one flat list.
Fixes #4245 
Removes <*li> for the divider as well as the Web Policies header, so that all policies are in the same list.
< Please provide screenshots if this will facilitate a faster review of these changes>

Fixes #4245 - Puts All Policies In Dropdown Navigation In Same List

---

app/Filament/Admin/Resources/AccountResource/Pages/ListAccounts.php

Fixes #4193
When searching with a CID on the accounts page of the admin panel, when there is one result it navigates you straight to that member.
https://github.com/user-attachments/assets/d3be5ce9-dc2d-4d9c-b17f-ddd3643cd762
Wasn't sure how to show this as a screenshot so I figured a short video would be best.

Fixes #4193 - Instant search result navigation for account search

---

.development/hooks/pre-commit

If the pre-commit exits with `0`, the commit gets created which is unwanted if pint made changes.
Now the hook will exit with an error code and force the user to re-add and commit again if changes were made.
*Commiting  in the hook itself is considered unsafe generally*

Make pre-commit exit with error if changes were made by pint

---

resources/views/components/nav.blade.php

Fix #4267
Removed the unnecessary separator (divider) at the end of the Pilots dropdown in the navigation bar.

Removed unnecessary separator from Pilots dropdown

---

app/Filament/Admin/Resources/AccountResource/RelationManagers/RetentionChecksRelationManager.php
app/Http/Controllers/Mship/WaitingLists.php
app/Models/Training/WaitingList/WaitingListRetentionCheck.php
tests/Feature/Training/RetentionCheckTokenTest.php

- Status `used` is now rendered as `responded` via the `statusHuman` accessor
- Checks are now sorted from latest by default
- If a token has already been used and a user tries to re-use it, they will be informed of the confirmed list place instead of being given a fail message

Retention checks QOL

---

app/Http/Controllers/Mship/WaitingLists.php
resources/views/livewire/retention-checks/success.blade.php
tests/Feature/Training/RetentionCheckTokenTest.php

After some thought, it's probably better to redirect to success page if a retention token has already been used.

Use success page for used retention token instead of fail

---

app/Console/Commands/Roster/UpdateRoster.php
app/Models/Training/WaitingList.php
database/seeders/WaitingListStressSeeder.php

Properly remove people from waiting lists on roster removal (going through normal removal steps). Add better notes on waiting list removal
Fixes TECH-397
Fixes TECH-415
Fixes #4283 
Accounts now go through the "normal" waiting list removal process during removals arising from roster changes. 
The note attached to the account now includes the join date and position at time of removal. This feature may cause issues when running in production due to the large amount of position calculation that takes place. 
< Please provide screenshots if this will facilitate a faster review of these changes>

TECH-415 / TECH-397 Waiting List Removals on Roster Removal & Notes
